### ISSUE TITLE
Revise logger

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#107]
Currently, the logger is set up in the example files, eDisGo_run() and other scripts directly at the top of the file. This introduces duplication and makes it difficult to re-use logger definitions elsewhere. Additionally, there are requests for finer control of logging parameters when using the logger.

TODOs
- Create a setup function for the logger, similar to [ding0's logger](https://github.com/openego/ding0/blob/a46a76f296319406313e400a5b4ce065db96bbde/ding0/tools/logger.py#L70-#L109)
- Provide following choices to the user for parametrization of the logger
  - Custom location
  - Custom file name
  - Define loglevel individually for StreamHandler and FileHandler
- Make it possible to include log information of depending packages, such like PyPSA

**Comment by khelfen** [comment]
This is a duplicate for #42 . I'll close this one and link it to the first issue
