### ISSUE TITLE
ETraGoSpecs without battery capacity and active power runtime takes too long or never finishes execution

### ISSUE THREAD

**Issue by boltbeard** [openego/eDisGo#114]
Using the minimal ETraGoSpecs example, and commenting out the input parameters `battery_capacity` and `battery_active_power` does not complete execution, the script keeps on running with no end, sort of like running an infinite loop.

**Comment by birgits** [comment]
@boltbeard I just moved the storage integration and curtailment parts into an `if ... is not None`. That should fix it.

**Comment by boltbeard** [comment]
Thanks @birgits, I see the commit https://github.com/openego/eDisGo/commit/8d895ae39295b59ac05c3c5538cfc1c8d0c957a1 
I'm closing this issue right now. If it needs to be revisited later, do re-open it
