### ISSUE TITLE
Matplotlib dependency in grids.py

### ISSUE THREAD

**Issue by boltbeard** [openego/eDisGo#115]
In ``edisgo/grid/grid.py`` there is a function ``draw()`` function in the class ``MVGrid`` which uses pyplot to draw a figure and show the network. The problem is that ``matplotlib`` isn't declared as a required package in ``setup.py``. This hinders eDisGo's installation as a standalone. @nesnoj may have just wanted to have some fun and induced this error to see who catches this!

Currently this function seems to be almost unused, is it absolutely necessary to have a giant library like matplotlib installed at all for the functionality of eDisGo?

There are the following solutions to address this:

1. remove the ``plt.figure()`` and ``plt.show()`` thereby removing the dependency on and if the draw function needs to be used, force the user to install ``matplotlib`` and use as shown below:
```python
from eDisGo import EDisGo
from matplotlib import pyplot as plt

edisgo_grid = EDisGo(...)

plt.figure()
edisgo_grid.draw()
plt.show()
```

2. use ``importlib`` and check if the user has ``matplotlib`` installed and force the user to install ``matplotlib`` externally if it not there. The check can be implemented as mentioned in [this stackoverflow question](https://stackoverflow.com/questions/14050281/how-to-check-if-a-python-module-exists-without-importing-it)

3. remove the ``draw()`` function all together and use the ``networkx`` graph with some plotting library outside of eDisGo?

It would be also nice to know why this draw function was integrated at all? What was the reason for this?

**Comment by boltbeard** [comment]
> I like the idea of having a conditional import, e.g. a debug mode in which matplotlib is imported. But as eGo is running out of time, this is a nice-to-have feature from my point of view..

@nesnoj, @gplssm suggested this too, but as you said it is a nice to have, question is - is there a temporary fix till this can be addressed?

**Comment by nesnoj** [comment]
To understand you correctly: by "fix" you mean to get rid of matplotlib in eDisGo, right?

**Comment by boltbeard** [comment]
@nesnoj, yes, if you have a better idea than the three solutions before do let me know..
