### ISSUE TITLE
Fix bugs in DINGO-Dataset

### ISSUE THREAD

**Issue by jochenbuehler** [openego/eDisGo#12]
It looks like there is a bug in MVGD 1833. The two marked cable distributers seem to have no purpose

![bug_in_mvgd_1833](https://user-images.githubusercontent.com/28706452/28514922-0f459f60-705c-11e7-86b8-c8efed298baf.png)

**Comment by nesnoj** [comment]
There's nothing without purpose! ;)
Seriously, why did u close the issue?
