### ISSUE TITLE
Ding0 import through csv  has missing elements in comparison to pickle file import

### ISSUE THREAD

**Issue by boltbeard** [openego/eDisGo#128]
The following elements are not correctly imported into eDisGo from the csvs:
### Critical
- [ ] MV Disconnector elements
- [ ] network._ding0_import_data is empty in case of CSV import (in case of .pkl DF)
- [x] Aggregated generators still have level 7 assigned in CSV files ~~(should be level 4)~~ **Update**: due to changes in how aggregated generators are sent to eDisGo level 4 is good
- [ ] MV lines connecting aggregated generators, aggregated loads and other buses and disconnector elements: Disconnecting points in CSV are missing plus the corresponding lines. To verify: check total line length
- [ ] Buses don't seem to be completely imported: in the pypsa object number of buses deviates
- [ ] network.mv_grid.station.transformers are not being imported correctly: half (at least less) nominal power in CSV files
- [ ] Discrepancy in peak load of loads
- [ ] Handling of missing attribute `name` of `line.type` is [located in reinforcement](https://github.com/openego/eDisGo/blob/8f741e0fe31e2a7f9f1710764353dfd5f83b6ea2/edisgo/flex_opt/reinforce_grid.py#L36-#L49), move it to the importer
- [ ] MV Transformer imports was not checked until now. There is a need for further checks
- [ ] Check why the `mvlv_mapping` csv is not being used

This has to be fixed before merging #106

**Comment by birgits** [comment]
Obsolete, as ding0 now exports csv files that are directly imported in eDisGo.
