### ISSUE TITLE
Missing weather cell ID for imported generators

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#133]
Generators imported upon calling edisgo.import_generators() don't have a weather cell ID which produces an error when calling their time series. We need to fix that as soon as possible since the ego tool relies upon it! @gplssm and @boltbeard who of you could do it?

**Comment by boltbeard** [comment]
Fixed in commit https://github.com/openego/eDisGo/commit/9e897629557953583ac3c40fccc74fc8508a7e69
