### ISSUE TITLE
Grid reinforcement before generator import

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#134]
A number of ding0 grids have over-loading or over-voltage issues using the edisgo check functions. One reason for this may be the different worst case assumptions, reactive power factors, load factors and allowed voltage deviations. 

edisgo:
* [load factors](https://github.com/openego/eDisGo/blob/dev/edisgo/config/config_grid_expansion_default.cfg#L62-L75)
* [allowed voltage deviations](https://github.com/openego/eDisGo/blob/dev/edisgo/config/config_grid_expansion_default.cfg#L19-L60)
* [worst-case assumptions](https://github.com/openego/eDisGo/blob/dev/edisgo/config/config_timeseries_default.cfg#L13-L40)
* [reactive power factors](https://github.com/openego/eDisGo/blob/dev/edisgo/config/config_timeseries_default.cfg#L42-L51)

ding0:
* [load factors](https://github.com/openego/ding0/blob/dev/ding0/config/config_calc.cfg#L67-L85)
* [allowed voltage deviations](https://github.com/openego/ding0/blob/dev/ding0/config/config_calc.cfg#L120-L137)
* [worst-case assumptions](https://github.com/openego/ding0/blob/dev/ding0/config/config_calc.cfg#L114-L118)
* [reactive power factors](https://github.com/openego/ding0/blob/dev/ding0/config/config_calc.cfg#L87-L89)

Values for comparison:
* [dena Verteilnetzstudie](https://shop.dena.de/fileadmin/denashop/media/Downloads_Dateien/esd/9100_dena-Verteilnetzstudie_Abschlussbericht.pdf)
** load factors: p. 90
** allowed voltage deviations: p. 92
** worst-case assumptions: p. 98
** reactive power factors: p. 114
* [BW Verteilnetzstudie](https://um.baden-wuerttemberg.de/fileadmin/redaktion/m-um/intern/Dateien/Dokumente/5_Energie/Versorgungssicherheit/170413_Verteilnetzstudie_BW.pdf)
** load factors: p. 37
** allowed voltage deviations: p. 38/39
** worst-case assumptions: p. 35
** reactive power factors: keine Angabe

**Comment by birgits** [comment]
Using the same parameters did not solve this issue. I noticed that the 10% criteria (allowed voltage deviation) was not satisfied upon importing the ding0 grid. We could now check if load and generation capacities are really the same by checking the pypsa representations of the ding0 and the edisgo grid.

**Comment by birgits** [comment]
As I found out ding0 only reinforces grids by using bigger cables. If the biggest available cable does not solve the issues, ding0 raises a warning. Therefore, it makes sense, that the ding0 grids are not stable when imported to edisgo. I have not checked for how many grids this is true and if only those issues known to ding0 are found by edisgo, but I think what we have to sort out first is if this was intended by ding0 or if we should solve it at some point. @nesnoj any opinion on it?

**Comment by jome1** [comment]
Is there an update on this issue?

**Comment by birgits** [comment]
We are currently working on this on the ding0 side and found some issues. Once all the so far known issues are solved there we will give an update here.

**Comment by birgits** [comment]
We should check this again and if it is still an issue check some of the points in #80.

**Comment by birgits** [comment]
The reason for this is that ding0 does not build parallel lines and transformers. We circumvented this now by running the eDisGo grid reinforcement after generating the grids in ding0. It is not planned in the near future to adapt ding0. I'll close this issue, as it is not an eDisGo issue.
