### ISSUE TITLE
Extend results of eDisGo

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#138]
The following results should be included in `EDisGo.network.results`

* Grid losses (in temporal scale of grid analysis)
* P and Q time series at the HV/MV substation

Maybe it makes sense to restructure the results object accordingly. Please, think of that while planning how to address this issues.

**Comment by boltbeard** [comment]
### Task list:
- [ ] Check pypsa documentation to see if losses are already provided in a convenient/default way
- [ ] Add the losses into Results()
