### ISSUE TITLE
Overwrite some eDisGo configurations with eGo

### ISSUE THREAD

**Issue by maltesc** [openego/eDisGo#149]
In the course of the restructuring of eGo's scenario settings (c.f. https://github.com/openego/eGo/issues/94), it seems to be reasonable to overwrite two parameters from eDisGo's configuration in order to facilitate working with consistent data. This should prevent from surprises by forgotten adjustments in eDisGo's config files.

In particular the parameters are:
**1) "db": "oedb" 
2) "gridversion": "v0.4.5"**

The question is **where to make this adjustment.** @birgits would it be an option to implement the overwriting in eDisGo - means to offer an API for eGo where these two parameters can be set?
Or is there an option to change these parameter without touching eDisGo's code (which I think would be preferable). E.g. something like:

```
edisgo_grid = EDisGo(ding0_grid=ding0_filepath)
edisgo_grid.here_is_the_parameter_i_want_to_change = "v0.4.5"
```

**Comment by maltesc** [comment]
@birgits thank you very much for the good information!
I just implemented the overwriting of the eDisGo configurations (cf. https://github.com/openego/eGo/blob/ec0711d734e951198193c9d347c1c12a0ac3d8a8/ego/tools/edisgo_integration.py#L166-L242). Could you please have a quick look, if I understood the lines correctly? Thank you!

**Comment by birgits** [comment]
Looks good! I wouldn't inform the user when edisgo and ego inputs match though, but that's a matter of taste.
