### ISSUE TITLE
Bug in switch disconnector positioning

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#150]
With the current dp version 0.4.5 there are 260 ding0 grids that cannot be imported due to a bug in the switch disconnector positioning. I think that the bug occurs when [position](https://github.com/openego/eDisGo/blob/8dab8d7c0a3430df4331b5599cd4ec89332edfa8/edisgo/grid/tools.py#L197) is zero, as the first and last node in `ring` are not connected (MV station is in between). A solution to this could be to not allow `position` to be zero. I am just not sure what this entails.
Another thing I was wondering about is why [here](https://github.com/openego/eDisGo/blob/8dab8d7c0a3430df4331b5599cd4ec89332edfa8/edisgo/grid/tools.py#L197) `ring[ctr - 2]` is used instead of `ring[ctr]`. Maybe this could also be part of the problem.
Can anyone help on this?

**Comment by nesnoj** [comment]
Is this one still relevant?

**Comment by birgits** [comment]
Yap, it is.

**Comment by birgits** [comment]
This is obsolete as we now directly import ding0 grids and do not reposition the switch.
