### ISSUE TITLE
i_res calculation

### ISSUE THREAD

**Issue by Deki4** [openego/eDisGo#152]
Should the _i_res calculation in tools.pypsa_io include a factor of sqrt(3)? I recently asked this question to the PyPSA creators and this was their answer: 
https://groups.google.com/d/msg/pypsa/uCs8vEpsip8/_HJAQXHZEwAJ

**Comment by birgits** [comment]
Sorry @Deki4 for getting back to you so late and thank you for posting this issue! I had a quick look and it looks like sqrt(3) should be inside the parenthesis [here](https://github.com/openego/eDisGo/blob/dev/edisgo/tools/pypsa_io.py#L1288-L1291). I want to check it thoroughly before pushing a fix, but am not sure when I'll have time to get to it. Definitely this month though.

**Comment by Deki4** [comment]
Hi Birgit,

No problem! I guess I have an older version of edisgo on my computer and it
seems to be fixed in this new version.

Thanks!
