### ISSUE TITLE
stats for eDisGo networks

### ISSUE THREAD

**Issue by jome1** [openego/eDisGo#157]
Is there any oppurtunity to get the length of added cables/lines and changed cables/lines after eDisGo reinforcement for a scenario? 
equipment_changes.csv gives change (added or changed) but no length and 
grid_expansion_costs.csv gives length but not if something was added or changed

It is not possible to merge these two dataframes appropiately.

**Comment by birgits** [comment]
If you want to get this information from the exported results you could join the equipment_changes table with the lines table from the pypsa network export (stored in pypsa_network/lines.csv). You could also add the length information to equipment_changes during execution. The index of equipment_changes contains the Line object which has the attribute length.

`edisgo.network.results.equipment_changes['length'] = [_.length if isinstance(_, Line) else np.nan for _ in edisgo.network.results.equipment_changes.index]`

I hope this helps!
