### ISSUE TITLE
OPF: Result Indexing incorrect when a subset of nodes is used for potential storage units

### ISSUE THREAD

**Issue by jadeaffenjaeger** [openego/eDisGo#165]
Currently the list of all buses is used to index the optimization results for storage units.

https://github.com/openego/eDisGo/blob/4de504ecea91cfa14952091fe3cf19d4a47a91ce/edisgo/opf/results/opf_result_class.py#L147

This will lead to wrong indexing if only a subset of nodes is used for potential storage units.

Proposed solution: Store list of storage buses from `run_mp_opf()` function call and use for reindexing when reading in results.

**Comment by jadeaffenjaeger** [comment]
Currently, the list of nodes for potential storage units is also passed directly from Python (which uses zero-based indexing) into Julia (which uses one-based indexing). This will cause different nodes than the expected ones to be considered for storage positioning.

Proposed solution: Argument should be a list of node names that gets converted to Integer indices.

**Comment by birgits** [comment]
@jadeaffenjaeger thanks for finding this! Are you fixing this yourself or do you need help with it?

**Comment by jadeaffenjaeger** [comment]
I'll fix it as soon as time permits.
