### ISSUE TITLE
How to deal with new PyPSA versions in eDisGo

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#17]
Currently, we use PyPSA v0.8.0 in Dingo. As Dingo is a dependency of eDisGo versions of dependent packages must be harmonized. I would like to stick closely to the latest version of PyPSA in eDisGo since up-to-date version include bug fixes and potential speed improvements. 

Two questions

1. Is there a way to define disjunct version numbers in dependent packages?
2. If 1. turns false, what version we like to take and how often do we want to upgrade in eDisGo **and** Ding0?

**Comment by nesnoj** [comment]
Concerning..
1. Seems to be possible, but the installation could require [some manual work](https://stackoverflow.com/questions/6570635/installing-multiple-versions-of-a-package-with-pip).. This does not seem to be a good solution to me.
2. I propose to update dingo every time eDisGo is updated. We might draft a workflow on "how to update pyPSA version" (including regression test of one grid in dingo to approve it).

There is a very good article on this: ["The nine circles of python dependency hell"](https://tech.knewton.com/blog/2015/09/the-nine-circles-of-python-dependency-hell/). Case 4 deals with so-called overlapping "transitive dependencies".

**Comment by nesnoj** [comment]
A general discussion takes place in #22

**Comment by gplssm** [comment]
For now, let's keep the manual update procedure. If required, re-open this issue
