### ISSUE TITLE
AttributeError when running tests - Fix using SQLAlchemy < 1.4.0

### ISSUE THREAD

**Issue by mltja** [openego/eDisGo#172]
Following tests failed with AttributeError if SQLAlchemy is >= 1.4.0. Fix: add in [setup.py](https://github.com/openego/eDisGo/blob/046cbd48036ee7a1014ed74290550c060d281e47/setup.py#L51) `'sqlalchemy <= 1.3.24'`

> FAILED tests/test_edisgo.py::TestEDisGo::test_edisgo_timeseries_analysis - AttributeError: 'Select' object has no attribute 'use_labels'
> FAILED tests/io/test_timeseries_import.py::TestTimeseriesImport::test_import_feedin_timeseries - AttributeError: 'Select' object has no attribute 'use_labels'
> FAILED tests/network/test_timeseries.py::Testget_component_timeseries::test_timeseries_imported - AttributeError: 'Select' object has no attribute 'use_labels'
> FAILED tests/network/test_timeseries.py::Testget_component_timeseries::test_add_loads_timeseries - AttributeError: 'Select' object has no attribute 'use_labels'
> FAILED tests/network/test_timeseries.py::Testget_component_timeseries::test_add_generators_timeseries - AttributeError: 'Select' object has no attribute 'use_labels'
> FAILED tests/network/test_timeseries.py::Testget_component_timeseries::test_add_storage_unit_timeseries - AttributeError: 'Select' object has no attribute 'use_labels'

**Comment by birgits** [comment]
Fixed with PR #181. Problem lies in egoio and needs to fixed there. We now just limit the upper version to be smaller than 0.1.4.
