### ISSUE TITLE
Question: Total lines disparity between EDisGo and Ding0 data

### ISSUE THREAD

**Issue by serpoten** [openego/eDisGo#176]
Hello,

I have created some networks using Ding0 directly. Their ID's are in the .csv file attached in the issue.

I came across while trying to understand the files generated, that the total number of lines are not the same, although the pickle is used in Ding0 for data statistics extraction and in eDisgo.

While `dingo.tools.resutls.calculate_mvgd_stats(network)`  provides the total number of `Number of LV branches` and `Number of MV branches`, in some cases the total number when summed is not the same as the total number of line generated in the pypsa eDisgo `lines.csv` file.

Is there a reason for this disparity?

[total_network_lines.csv](https://github.com/openego/eDisGo/files/6404807/total_network_lines.csv)

**Comment by birgits** [comment]
Hi @serpoten, are you using the latest versions of ding0 and eDisGo from PyPI or did you install from github?

**Comment by serpoten** [comment]
Hi!

From ding0 I am using the git-hub whereas for the eDisGo I am using the PyPI.

**Comment by birgits** [comment]
I would assume that it has got to do with aggregated load areas. Can you check if those grid districts where there is a disparity have aggregated load areas? I think that in ding0 these areas are connected to the HV-MV station by one line (I would have to check with the ding0 people though) whereas in eDisGo generators and loads in those areas are aggregated by type/sector and each type/sector is connected independently.

**Comment by serpoten** [comment]
Indeed these ones have "LV station (aggregated)".

**Comment by birgits** [comment]
I will close this issue. If you do not think it is solved @serpoten you can reopen it.
