### ISSUE TITLE
Bug - Failing of: test_integrate_component

### ISSUE THREAD

**Issue by mltja** [openego/eDisGo#179]
When running test in debug-mode all is fine until:
test_edisgo.py in l.581:

    comp_name = self.edisgo.integrate_component(
        comp_type="ChargingPoint",
        geolocation=geom,
        ts_active_power=ts_active_power,
        ts_reactive_power=ts_reactive_power,
        **comp_data
    )

In function integrate_component in l.1281 the "BusBar_MVGrid_1_LVGrid_1_LV" is found but 
"BusBar_MVGrid_1_LVGrid_1_LV" doesn't exists in self.edisgo.topology.charging_points_df.at[comp_name, "bus"]

            substations = self.topology.buses_df.loc[
                self.topology.transformers_df.bus1]
            nearest_substation, _ = find_nearest_bus(geolocation, substations)  #<-- l.1281
            kwargs['mvlv_subst_id'] = int(nearest_substation.split("_")[-2])
            kwargs['geom'] = geolocation
            kwargs['voltage_level'] = voltage_level
            comp_name = self.topology.connect_to_lv(self, kwargs, comp_type)

## Error Code

    FAILED              [100%]
    tests/test_edisgo.py:487 (TestEDisGo.test_integrate_component)
    Bus_Load_agricultural_LVGrid_1_3 != BusBar_MVGrid_1_LVGrid_1_LV
    
    Expected :BusBar_MVGrid_1_LVGrid_1_LV
    Actual   :Bus_Load_agricultural_LVGrid_1_3
    <Click to see difference>
    
    self = <test_edisgo.TestEDisGo object at 0x7f3e57639080>
    
        def test_integrate_component(self):
            """Test integrate_component method"""
            num_gens = len(self.edisgo.topology.generators_df)
        
            random_bus = self.edisgo.topology.buses_df.index[10]
            x = self.edisgo.topology.buses_df.at[random_bus, "x"]
            y = self.edisgo.topology.buses_df.at[random_bus, "y"]
            geom = Point((x, y))
        
            # ##### MV integration
            # test generator integration by voltage level, geom as tuple, without
            # time series
            comp_data = {
                "generator_id": 13,
                "p_nom": 4,
                "generator_type": "misc",
                "subtype": "misc_sub"
            }
            comp_name = self.edisgo.integrate_component(
                comp_type="Generator",
                geolocation=(x, y),
                voltage_level=4,
                add_ts=False,
                **comp_data
            )
        
            assert len(self.edisgo.topology.generators_df) == num_gens + 1
            assert (self.edisgo.topology.generators_df.at[comp_name, "subtype"] ==
                    "misc_sub")
            # check that generator is directly connected to HV/MV station
            assert self.edisgo.topology.get_connected_lines_from_bus(
                self.edisgo.topology.generators_df.at[comp_name, "bus"]
            ).bus0[0] == "Bus_MVStation_1"
        
            # test charging point integration by nominal power, geom as shapely
            # Point, with time series
            num_cps = len(self.edisgo.topology.charging_points_df)
        
            comp_data = {
                "p_nom": 4,
                "use_case": "fast"
            }
            ts_active_power = pd.Series(
                data=[1, 2],
                index=self.edisgo.timeseries.timeindex
            )
            ts_reactive_power = pd.Series(
                data=[0, 0],
                index=self.edisgo.timeseries.timeindex
            )
            comp_name = self.edisgo.integrate_component(
                comp_type="ChargingPoint",
                geolocation=geom,
                ts_active_power=ts_active_power,
                ts_reactive_power=ts_reactive_power,
                **comp_data
            )
        
            assert len(self.edisgo.topology.charging_points_df) == num_cps + 1
            assert (self.edisgo.topology.charging_points_df.at[
                        comp_name, "use_case"] == "fast")
            # check voltage level
            assert self.edisgo.topology.buses_df.at[
                self.edisgo.topology.charging_points_df.at[comp_name, "bus"],
                "v_nom"] == 20
            # check that charging point is connected to the random bus chosen
            # above
            assert self.edisgo.topology.get_connected_lines_from_bus(
                self.edisgo.topology.charging_points_df.at[comp_name, "bus"]
            ).bus0[0] == random_bus
            # check time series
            assert (self.edisgo.timeseries.charging_points_active_power.loc[
                    :, comp_name].values == [1, 2]).all()
            assert (self.edisgo.timeseries.charging_points_reactive_power.loc[
                    :, comp_name].values == [0, 0]).all()
        
            # ##### LV integration
        
            # test charging point integration by nominal power, geom as shapely
            # Point, with time series
            comp_data = {
                "number": 13,
                "p_nom": 0.04,
                "use_case": "fast"
            }
            ts_active_power = pd.Series(
                data=[1, 2],
                index=self.edisgo.timeseries.timeindex
            )
            ts_reactive_power = pd.Series(
                data=[0, 0],
                index=self.edisgo.timeseries.timeindex
            )
            comp_name = self.edisgo.integrate_component(
                comp_type="ChargingPoint",
                geolocation=geom,
                ts_active_power=ts_active_power,
                ts_reactive_power=ts_reactive_power,
                **comp_data
            )
        
            assert len(self.edisgo.topology.charging_points_df) == num_cps + 2
            assert (self.edisgo.topology.charging_points_df.at[
                        comp_name, "number"] == 13)
            # check bus
    >       assert self.edisgo.topology.charging_points_df.at[
                       comp_name, "bus"] == "BusBar_MVGrid_1_LVGrid_1_LV"
    E       AssertionError: assert 'Bus_Load_agricultural_LVGrid_1_3' == 'BusBar_MVGrid_1_LVGrid_1_LV'
    
    test_edisgo.py:593: AssertionError

**Comment by birgits** [comment]
Fixed in #177.
