### ISSUE TITLE
Test eDisGo with ding0 v0.2.1

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#182]
I just created the [release v0.2.1 of ding0](https://github.com/openego/ding0/releases/tag/v0.2.1) (also on PyPI).

Could you please test if eDisGo is compatible with the new version? At least the CSV format has changed but there're more things which might affect eDisGo, cf. [changelog of 0.2.0](https://github.com/openego/ding0/releases/tag/v0.2.0) (0.2.1 was just an install fix)

**Comment by birgits** [comment]
Yeah, congratulations on the new release :) I will check compatibility and hopefully make a new eDisGo release as well!

**Comment by birgits** [comment]
Has been checked and eDisGo released :)
