### ISSUE TITLE
make HV-MV substations "smart"

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#20]
As a future flexibility, HV-MV substations could automatically adjust their secondary voltage according to the current flow (already used by some DSOs, more details in Wupp. study).
(copied from https://github.com/openego/ding0/issues/136)

**Comment by gplssm** [comment]
@jochenbuehler recommends to not specifically model HV-MV transformers in detail. Only check current rating by simplified method and assume a fixed voltage at secondary side.
