### ISSUE TITLE
Keep raising error in case power flow does not converge for all time steps?

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#207]
Currently an [error is raised](https://github.com/openego/eDisGo/blob/dev/edisgo/edisgo.py#L492) when power flow did not converge for all time steps and results of the power flow are lost, even for time steps that did converge. I think we should change that behavior as it is sometimes helpful to at least get the results of converged time steps and handle the not converged ones differently. I propose writing the results of the converged time steps to the Results class in any case. We could further make raising an error optional, so that it can be suppressed by the user if raising an error is not wanted. @khelfen and @AnyaHe what do you think?

We could also add a function that implements the [trouble shooting for non-convergence proposed by pypsa](https://pypsa.readthedocs.io/en/latest/troubleshooting.html#problems-with-power-flow-convergence)?

**Comment by khelfen** [comment]
Yes, I already wanted to implement that a while ago :D I'll assign the issue to me

**Comment by AnyaHe** [comment]
Looks good to me. Thank you :)

**Comment by birgits** [comment]
@khelfen suggested also giving out a warning, in case error raising behavior is suppressed. I added this and will now close this issue.
