### ISSUE TITLE
Grid reinforcement using ten percent criterion

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#209]
The current [grid reinforcement function](https://github.com/openego/eDisGo/blob/dev/edisgo/flex_opt/reinforce_grid.py#L13) allows using the ten percent criterion instead of separate voltage limits for each voltage level. However, the implemented methodology does not handle this case very well. If voltage rise or drop in the MV is already quite high, then reinforcing the lower voltage levels might not solve exceedance of the ten percent criterion in these voltage levels. 

@khelfen and @AnyaHe, my first question is, do we want to keep this option? If so, wen need to find a way to decide, whether to reinforce the MV, MV/LV or LV level.

This issue is closely linked to #208 and #203.

**Comment by AnyaHe** [comment]
It should not be too difficult to extract the percentage of voltage drop in MV, MV/LV and LV level, right? We would just have to look at the transformer. With that, we could come up with some threshold value which decides whether the MV should be reinforced or not. Although it probably also depends on the number of underlying LV grids that show voltage violations if it makes more sense to reinforce in the MV or not.

**Comment by birgits** [comment]
Overlaps with #350. I'll therefore close this issue.
