### ISSUE TITLE
Calculation of reactance

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#213]
When calculating the reactance of a line in [this function](https://github.com/openego/eDisGo/blob/dev/edisgo/tools/tools.py#L116-L137) we currently neglect die capacitive reactance. As @AnyaHe found in a paper, the effect on this on reactive power can be quite significant. (@AnyaHe could you please add a link to the mentioned paper?) We should therefore add it in the above mentioned function. See [here](https://electronicsclub.info/impedance.htm) for further information on this.

- [ ] Add capacitive reactance to function [calculate_line_reactance](https://github.com/openego/eDisGo/blob/dev/edisgo/tools/tools.py#L116-L137)
- [ ] Change [this line](https://github.com/openego/eDisGo/blob/dev/edisgo/network/topology.py#L1306) to use calculate_line_reactance function
- [ ] Add C_per_km for [LV cables](https://github.com/openego/eDisGo/blob/dev/edisgo/equipment/equipment-parameters_LV_cables.csv) (see if information is available in [pandapower](https://pandapower.readthedocs.io/en/develop/std_types/basic.html#lines) data)
- [ ] Check C_per_km for MV [cables](https://github.com/openego/eDisGo/blob/dev/edisgo/equipment/equipment-parameters_MV_cables.csv) and [overhead lines](https://github.com/openego/eDisGo/blob/dev/edisgo/equipment/equipment-parameters_MV_overhead_lines.csv) with values in [pandapower](https://pandapower.readthedocs.io/en/develop/std_types/basic.html#lines)
- [ ] Check difference between including and neglecting capacitive reactance

**Comment by AnyaHe** [comment]
Here is the link of the paper mentioned: https://eprints.whiterose.ac.uk/178191/1/ISGT_2021_Agnes.pdf

**Comment by AnyaHe** [comment]
Would it not also be a possibility to include C when translating the problem to PyPSA instead of changing the calculation of the reactance in eDisGo?
