### ISSUE TITLE
Unclutter aggregation functionality

### ISSUE THREAD

**Issue by khelfen** [openego/eDisGo#226]
At the moment the `aggregate_components` functionality makes up a substantial part of the main `edisgo.py`. It would be nice to unclutter the `aggregate_components` functionality by putting it into individual functions into the `tools` (?) module and just calling them from the main.

**Comment by khelfen** [comment]
Please make sure #225 is closed beforehand

**Comment by birgits** [comment]
I uncluttered it [here](https://github.com/openego/eDisGo/blob/features/restructure_time_series/edisgo/edisgo.py#L924-L1029).
