### ISSUE TITLE
Add consistency check for edisgo object

### ISSUE THREAD

**Issue by AnyaHe** [openego/eDisGo#231]
If manipulating the edisgo object after creating it, it would be nice to have a function that checks the consistency of the whole object. The method should:

- [x] check whether the topology itself is consistent (use _validate_ding0_grid_import: https://github.com/openego/eDisGo/blob/974c2dbaba4592fbaf7fc60fc463576dd05b6750/edisgo/io/ding0_import.py#L130 ),
- [x] check whether all components in topology have an entry in the respective active and reactive power timeseries,
- [x] check whether all elements in timeseries have an entry in the topology.
- [x] check if the powers inside the timeseries exceed the given nominal or peak power of the component

If any of these show inconsistencies, the method should throw a warning.

**Comment by khelfen** [comment]
We should also check if we could replace (parts of) our existing consistency check with the [consistency check offered by PyPSA](https://github.com/PyPSA/PyPSA/blob/4cc14b76363183fb56fcae451cb4fc8ccb423b70/pypsa/components.py#L1149-L1161)

**Comment by AnyaHe** [comment]
> We should also check if we could replace (parts of) our existing consistency check with the [consistency check offered by PyPSA](https://github.com/PyPSA/PyPSA/blob/4cc14b76363183fb56fcae451cb4fc8ccb423b70/pypsa/components.py#L1149-L1161)

- [ ] Use pypsa consistency check in _check_integrity_of_pypsa

**Comment by AnyaHe** [comment]
> > We should also check if we could replace (parts of) our existing consistency check with the [consistency check offered by PyPSA](https://github.com/PyPSA/PyPSA/blob/4cc14b76363183fb56fcae451cb4fc8ccb423b70/pypsa/components.py#L1149-L1161)
> 
>     * [ ]  Use pypsa consistency check in _check_integrity_of_pypsa

I tried to apply this: https://stackoverflow.com/questions/47415894/how-to-turn-logging-warnings-into-errors. However, I could not get it to work. Do you have any experience with catching logging messages from other packages @khelfen and @birgits ?

**Comment by AnyaHe** [comment]
> > > We should also check if we could replace (parts of) our existing consistency check with the [consistency check offered by PyPSA](https://github.com/PyPSA/PyPSA/blob/4cc14b76363183fb56fcae451cb4fc8ccb423b70/pypsa/components.py#L1149-L1161)
> > 
> > 
> > ```
> > * [ ]  Use pypsa consistency check in _check_integrity_of_pypsa
> > ```
> 
> I tried to apply this: https://stackoverflow.com/questions/47415894/how-to-turn-logging-warnings-into-errors. However, I could not get it to work. Do you have any experience with catching logging messages from other packages @khelfen and @birgits ?

In the end, we decided to stick with the tests we have as I could not resolve the issue and we would have to make sure we always keep track of the pypsa warnings.

**Comment by khelfen** [comment]
This issue is solved, right?
