### ISSUE TITLE
pypsa  R and X of transformers

### ISSUE THREAD

**Issue by fontempa** [openego/eDisGo#259]
Accoding to the user guide, when adding a transformer in the network, without specifying the type, the required input parameters are:
name, bus0, bus1, model, r, x, where r and x are intruduced in p.u.. Nonetheless, when running the code, the output of x_pu and r_pu are inf, and of course the simulation ends up given NaN results.

I'm trying to evaluate the IEEE 14 bus, and with the data given by the datasheet I end up facing the above problem.
Any advice?

**Comment by birgits** [comment]
I am not sure I understand your question @fontempa. In eDisGo the required transformer parameters are x_pu and r_pu (see [here](https://github.com/openego/eDisGo/blob/dev/edisgo/network/topology.py#L385-L389)). Only when importing from csv columns x and r are accepted and then renamed to x_pu and r_pu (see e.g. [here](https://github.com/openego/eDisGo/blob/dev/edisgo/io/ding0_import.py#L88-L91)). In pypsa they are also named x and r, so when exporting to the pypsa format, they are also renamed. Does that help you?

**Comment by fontempa** [comment]
@birgits  thank you for you comment. Actually, let's say I define my transformer like this:
network.add("Transformer", "Trx1", bus0 = "Bus No 2", bus1 = "Bus No 3", model = "pi", tap_ratio = 1, x=0.0029\09, r=0)

When I run this to check the dataframe, x_pu and r_pu both have "inf". I mean, If the entry of x and r above is directly in pu, then the values of x_pu and r_pu should be the same. I might be misunderstanding something though.

**Comment by birgits** [comment]
I think this is solely a pypsa question, right? Or how is eDisGo connected to your question?
In pypsa you specify x and r and x_pu and r_pu are outputs after the pf or lopf. x and x_pu should be the same if you are not allowing an extension of the transformer, that is right.

**Comment by fontempa** [comment]
@birgits my apologies!, I shoudln't have posted the question here. I was careless.
Thank you for your answer anyway.

**Comment by birgits** [comment]
No problem, I was just a bit confused and not quite sure if I got your question right. Good luck on solving your problem!

**Comment by birgits** [comment]
No problem, I was just a bit confused and not quite sure if I got your question right. Good luck on solving your problem!
