### ISSUE TITLE
config params in grid expansion

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#26]
Are there any parameters in the grid expansion module which the user should be able do modify? @birgits 
We should add them to config.
Please list here and I'll add them.

**Comment by birgits** [comment]
standard lines and transformers:
* I need [these](https://www.baden-wuerttemberg.de/fileadmin/redaktion/m-um/intern/Dateien/Dokumente/5_Energie/Versorgungssicherheit/170413_Verteilnetzstudie_BW.pdf#44) in the available components file
* as we discussed it would be good to define standard components used for the grid expansion in the config file

parameters for grid expansion:
* mv_max_v_deviation, lv_max_v_deviation - allowed voltage deviations
* load_factor_mv_lv_transformer,  load_factor_hv_mv_transformer (? - might be useful at some point)
* load_factor_mv_line, load_factor_lv_line - load factors are the same for cables and lines, we could also call these parameters load_factor_mv_cable? is there a word that means both line and cable?

That's it for now. Thank you!

**Comment by nesnoj** [comment]
All done. I created a pull request #29 to merge my current branch `features/#25-dir-and-config` to yours.

I created a new config file `config_flexopt.cfg` which contains params and std. components.

**Equipment**
- You can find equipment in `Network.equipment_data` (files loaded on instantiation)`
- Access to standard equipment via `Network.config['grid_expansion']['std_...']`

**Params**
- I took values from dingo, please **re-check**!
- Access to standard equipment via `Network.config['grid_expansion']['...']`

**Comment by birgits** [comment]
Thank you @nesnoj, it works perfectly!

Did you just want me to check the grid expansion config? I have some questions about it:
Do we want to use the standard parameters and components used in the BW study as defaults? Then I would change some stuff accordingly and maybe write a note in the config file. 
And I guess our unit consistency does apply not for names? Otherwise we'd have to rename the 40 MVA transformer to 40000 kVA... (I vote for 40 MVA.)

**Comment by nesnoj** [comment]
1. I already used the components from the BW study as default values in the config..(did I mess up something?)
2. Yes, I would keep 40 MVA as well.

**Comment by birgits** [comment]
Equipment is correct! I would just set load_factor_mv_line to 1.0 (instead of 0.6) since that is used for feedin case.
I am unsure about the default values for voltage deviation. We are going to use 0.1 since we're looking at MV and LV together. In the BW study they're using 3,5% in LV and 5% in MV plus 1,5% in MV/LV transformer. I would suggest using all the feed-in case values from the BW study for the default config.

**Comment by birgits** [comment]
I am not sure if this is the best place to discuss it but I just stumbled across an inconsistency between the config and the importer from dingo. Transformers from config have s_nom, R and X whereas imported transformers have s, r and x. I could fix this in the importer if you agree (in dev).

**Comment by nesnoj** [comment]
I tend to fix it in Dingo. I can do it if you don't mind.
Gimme a second to answer your previous question..

**Comment by nesnoj** [comment]
Uhh ok, I completely forgot about the other params :confounded:.

We want to allow the user to do the checks on MV+LV combined and separately, right?
Hence, we need different parameter sets for both cases (values from Dingo, sources: BDEW, VDR AR, LVN, Wupp. study). I'm ok with using slightly different params than in the BW study because is does not affect the method's core.
One more thing: If they use 5% + 1.5% + 3.5%, the assume an ideal voltage of 100% at HV-MV substation. I'm not sure if this is appropriate (see comment below).

Params I propose:

entity | load case | feedin case | comment
--- | -------------- | ---------------- | -----------------
Combined MV+LV | 11% | 6% | 10% according to DIN EN, but we have to consider a (usually) set voltage of 102.5% ± 1.5% offset at HV-MV substation )
MV grid only | 5% | 2% | -
LV grid only | 5% | 3% | -

@jochenbuehler @gplssm Please re-check these params (our favourite topic :smile:).

I would include the load case since we want to make eDisGo as generic as possible?!

**Comment by birgits** [comment]
> We want to allow the user to do the checks on MV+LV combined and separately, right?

Yes that's right!

> I would include the load case since we want to make eDisGo as generic as possible?!

For the grid expansion methodology it doesn't matter if load case or feed-in case is analysed. Therefore, I didn't include separate parameters for these two cases. If one wants to analyse the load case (s)he just has to adapt the parameters. But we could provide default parameters for both cases anyway and maybe have a switch in the config file whether to use feed-in or load case parameters as grid_expansion parameters?

**Comment by nesnoj** [comment]
> But we could provide default parameters for both cases anyway

yes, I'd do that.

>and maybe have a switch in the config file whether to use feed-in or load case parameters as grid_expansion parameters?

Sounds good. But I wouldn't use the config file because the user might want to use both in different cases. Maybe this could be done using an argument...?

**Comment by birgits** [comment]
I'll think about it!

**Comment by nesnoj** [comment]
> I tend to fix it in Dingo. I can do it if you don't mind.

Done in https://github.com/openego/ding0/commit/fbe76d04527c9cca7be9759066692354ef5d0933

**Comment by birgits** [comment]
@jochenbuehler and @gplssm, @nesnoj proposed voltage deviation values for load and feedin case a few days ago. Are we using those? Please check!

**Comment by gplssm** [comment]
> entity | load case | feedin case | comment
> --- | -------------- | ---------------- | -----------------
> Combined MV+LV | 11% | 6% | 10% according to DIN EN, but we have to consider a (usually) set voltage of 102.5% ± 1.5% offset at HV-MV substation, cf. Wupp. study)
> MV grid only | 5% | 2% | -
> LV grid only | 5% | 3% | -

@nesnoj thanks for the suggestion. Without further explanation or reading a lot I don't get it how you choose these values.

**Comment by nesnoj** [comment]
First row (combined case):
- you may refer to Fig 5-3 on p. 30 in the [Wupp. study](http://elpub.bib.uni-wuppertal.de/servlets/DerivateServlet/Derivate-5651/eaw0216.pdf). If I'm not mislead, we have to take the offset at HV-MV substation into account (don't we, @jochenbuehler?)

The latter 2 cases are taken from Dingo:
- The 2%/3% refer to BDEW and VDE-AR (simplified calculations)
- We used 2*5% = 10% (according to DIN EN) without offset, since these regulations prescribe to use the nominal voltage at HV-MV substation)

**Comment by birgits** [comment]
> But we could provide default parameters for both cases anyway and maybe have a switch in the config file whether to use feed-in or load case parameters as grid_expansion parameters?

> Sounds good. But I wouldn't use the config file because the user might want to use both in different cases. Maybe this could be done using an argument of your main method...?

The idea for now is to have the switch in the network object when loading the config parameters (so have all parameters for both cases in the configs but only load the parameters for the case that is analysed). This will be rethought though when restructuring the edisgo inputs. For now we leave it as it is and use feed-in case parameters in the config files since right now we want to calculate grid expansion costs due to renewables  expansion and imply that grids are already dimensioned for the load case.

**Comment by nesnoj** [comment]
ok

**Comment by gplssm** [comment]
Now, I understand the values for "Combined MV + LV". But we cannot say +6/-11%, because it depends on the offset (in Wuppertalstudie +2,5%) and the _Regelabweichung_ (+/-1,5%). Hence we could 

Load case: 10 % + offset (if postitive) - _Regelabweichung_ (=+/-1,5%) = 10 % - 1,5% + offset = 8,5% + offset
Feedin case: 10 % - offset (if postitive) - _Regelabweichung_ (=+/-1,5%)= 10 % - 1,5% - offset = 8,5% - offset

With an offset at HV-MV substation of 2,5% we have exactly 11% respectively 6 %.

**Comment by nesnoj** [comment]
Exactly! I just used "offset" for combined offset and Regelabweichung.
Let's add your more general description to the config, split into offset and control deviation.. this way we allow a more specific configuration..

**Comment by gplssm** [comment]
Then we have to consider the offset and _Regelabweichung_ in power flow analysis (which does currently not take place, v_set=1pu) and link allowed voltage deviation to these parameters.

**Comment by nesnoj** [comment]
can't you just pass it as sum to v_set?

**Comment by gplssm** [comment]
Yes, can do that. Sorry, i didn't want do confuse you...

**Comment by nesnoj** [comment]
Ok, If you have no further objections I'll implement it as described above..

**Comment by gplssm** [comment]
Go for it!

**Comment by nesnoj** [comment]
Done in af91fcbd35e187821eb543085f575afb0b3a8fde.
```
# allowed voltage deviations
# ==========================
# COMBINED MV+LV
# --------------
# hv_mv_trafo_offset:
#     offset which is set at HV-MV station
#     (pos. if op. voltage is increased, neg. if decreased)
hv_mv_trafo_offset = 0.025

# hv_mv_trafo_control_deviation:
#     control deviation of HV-MV station
#     (always pos. in config; pos. or neg. usage depending on case in edisgo)
hv_mv_trafo_control_deviation = 0.015

# mv_lv_max_v_deviation:
#     max. allowed voltage deviation according to DIN EN 50160
#     caution: offset and control deviation at HV-MV station must be considered in calculations!
mv_lv_max_v_deviation = 0.10

# MV ONLY
# -------
# mv_load_case_max_v_deviation:
#     max. allowed voltage deviation in MV grids (load case)
mv_load_case_max_v_deviation = 0.05

# mv_feedin_case_max_v_deviation:
#     max. allowed voltage deviation in MV grids (feedin case)
#     according to BDEW
mv_feedin_case_max_v_deviation = 0.02

# LV ONLY
# -------
# lv_feedin_case_max_v_deviation:
#     max. allowed voltage deviation in LV grids (load case)
lv_load_case_max_v_deviation = 0.05

# lv_feedin_case_max_v_deviation:
#     max. allowed voltage deviation in LV grids (feedin case)
#     according to VDE-AR-N 4105
lv_feedin_case_max_v_deviation = 0.03
```
As described above, the offset and control deviation at HV-MV substation must be considered in your code, e.g. for combined MV+LV grid for feedin case `ALLOWED_VOLTAGE_DEVIATION = mv_lv_max_v_deviation - hv_mv_trafo_offset - hv_mv_trafo_control_deviation` (=6%)

PS: Do not forget to remove your old config files in `~/.edisgo/config/` to allow edisgo to copy new versions. @birgits @gplssm

I close this issue, please reopen if u need more config params..

**Comment by birgits** [comment]
I want to keep this open until I implemented a way to choose between feedin and load case and have all parameters in the config adapted to it!

**Comment by birgits** [comment]
#94 also needs to be considered when including the load case.

**Comment by birgits** [comment]
@gplssm do I remember correctly that you asked Jochen about my question how we decide whether to use feed-in or load case parameters when doing grid expansion for timeseries and that he said that we just check the power at the HV/MV transformer? That would mean that we don't check for every LV grid which parameters to use but only for the whole distribution grid (MV and LV).

**Comment by birgits** [comment]
I just merged my implementation of differentiating load factors and allowed voltage deviations by load and feed-in case into dev (together with a few other changes) and documented it [here](https://github.com/openego/eDisGo/blob/dev/doc/features_in_detail.rst).
