### ISSUE TITLE
[FEATURE] Improvements concerning electromobility data import, testing and documentation

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#275]
The following things should be added/improved:

- [x] Expand tests #261
- [x] Use test grid 1 - needs changing of potential charging point locations so that they are inside the grid district
- [x] Move current tests to better fitting places (e.g. io functions should be tested in io)
- [x] Add documentation on how charging processes are allocated to charging stations (also concerns #274) 
- [x]  https://github.com/openego/eDisGo/issues/218
- [ ] (Allow newer version of SimBEV and TracBEV)

**Comment by birgits** [comment]
Should we leave this open or can we close it @khelfen?

**Comment by khelfen** [comment]
I think we can leave this open so we remember to update our imports according to the new SimBEV versions. We could also handle this in a separate issue.

**Comment by birgits** [comment]
A new issue would make sense!
