### ISSUE TITLE
conv. PP in future scenarios

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#28]
In the SQ scenario, there're 222 conv. PP in v_levels 4..7.
In NEP2035 we have 180 and in EGO100 we have 5 left.

1. The difference in PP count results from decommisioning, right?
2. In the 2 future scenarios, are any additional conv. PP installed?

If 1. is true, we must disconnect decommisioned conv. PP which were connected in dingo.

**Comment by gplssm** [comment]
I would say 1 is true. But it verification by @wolfbunke would be nice.

I agree on 2.

**Comment by wolfbunke** [comment]
I think this is a problem of the dataprocessing. At the moment @IlkaCu  was working on the voltage assignment.

**Comment by IlkaCu** [comment]
I doubt that this is caused by the DP. We assign the voltage level to every power plant according to its installed capacity and [here](https://github.com/openego/data_processing/blob/release/v0.3/preprocessing/sql_snippets/ego_pre_voltage_level.sql#L118-L126) we make sure that the voltage levels are consistent between the SQ and nep2035 scenario.

**Comment by nesnoj** [comment]
@wolfbunke Which part is a problem of dp?
Does the difference in PPs results from decommisioning?

**Comment by wolfbunke** [comment]
Without checking in detail I can say that we have  decommisioning from SQ to NEP 2035 and also a change of capacity of some plants.

**Comment by wolfbunke** [comment]
> If 1. is true, we must disconnect decommisioned conv. PP which were connected in dingo.

Yes, by using the Mviews of conv. and renewable power plants per scenario. A own selection based on the ego_dp_ tables via scenario etc. I wouldn't recommend due to changes etc..

**Comment by nesnoj** [comment]
damn, wrong button

**Comment by gplssm** [comment]
Is this one outdated?

**Comment by nesnoj** [comment]
yea, but further questions came up which are discussed here: https://github.com/openego/data_processing/issues/178
