### ISSUE TITLE
[BUG] Basic edisgo installation not working

### ISSUE THREAD

**Issue by khelfen** [openego/eDisGo#286]
**Describe the bug**
When installing edisgo without additional dependecies the import is failing because `plotly` is not installed and a neccessary `if`-clause when importing it is missing.

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [2], in <cell line: 9>()
      6 import networkx as nx
      7 import pandas as pd
----> 9 from edisgo import EDisGo

File ~/Documents/PythonProjects/edisgo_ws/edisgo/__init__.py:1, in <module>
----> 1 from edisgo.edisgo import EDisGo

File ~/Documents/PythonProjects/edisgo_ws/edisgo/edisgo.py:30, in <module>
     28 from edisgo.opf.results.opf_result_class import OPFResults
     29 from edisgo.opf.run_mp_opf import run_mp_opf
---> 30 from edisgo.tools import plots, tools
     31 from edisgo.tools.config import Config
     32 from edisgo.tools.geo import find_nearest_bus

File ~/Documents/PythonProjects/edisgo_ws/edisgo/tools/plots.py:12, in <module>
     10 import numpy as np
     11 import pandas as pd
---> 12 import plotly.graph_objects as go
     14 from dash import dcc, html
     15 from dash.dependencies import Input, Output

ModuleNotFoundError: No module named 'plotly'
```

**To Reproduce**
1. Setup new virtual env
2. Install edisgo with `pip install -e .`
3. Try to import `from edisgo import EDisGo` within any script

**Expected behavior**
No Error

**Comment by birgits** [comment]
We decided to only provide a basic installation (combining the current basic installation with the geoplot and examples installation) and a dev installation. The dev packages shouldn't impact the tests, wherefore we can run all tests using the basic installation. This then needs to be adapted in github actions. Further, we decided to also test Windows installation. @maike93he and @mltja please coordinate who will do what.

**Comment by mltja** [comment]
Tried it today with the dev branch and the basic installation, the error no longer occurs.

Minimum working example:
```
from edisgo import EDisGo

edisgo_obj = EDisGo()

print(edisgo_obj.config["grid_connection"]["branch_detour_factor"])
```
