### ISSUE TITLE
computation time of PF for combined MV+LV

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#30]
I'd like to get a better undestanding of how long a PF takes for an entire distribution grid (MV+LV) (1 timestep).

**Comment by gplssm** [comment]
eDisGo computation including import data from pickel and power flow analysis with a grid of

* buses: 16249
* generators: 574
* loads: 5114
* lines: 16107

takes 51 sec. The power flow analysis was exemplary performed for two timesteps. Those individually required around half of a second:

> INFO:pypsa.pf:Newton-Raphson solved in 3 iterations with error of 0.000000 in 0.490657 seconds
> INFO:pypsa.pf:Newton-Raphson solved in 3 iterations with error of 0.000000 in 0.516435 seconds

**Comment by nesnoj** [comment]
That's far less than I expected..
Did you use MVGD 134 resp. 3545 ?

**Comment by nesnoj** [comment]
I'm wondering if multiple cpu cores are supported by PyPSA in non-linear PF? @nworbmot
In my setup, only one core is used during PF.

PyPSA [uses numpy/scipy](https://pypsa.org/doc/introduction.html#what-pypsa-uses-under-the-hood) to solve the matrices in NR method. According to the [scipy docs](https://scipy.github.io/old-wiki/pages/ParallelProgramming), a different implementation is needed to use multiple cores.
Does PyPSA uses these capabilities?

**Comment by nworbmot** [comment]
PyPSA doesn't currently have multi-threading. The majority of time should be taken by solving the sparse linear equations, which is farmed by scipy out to the C library umfpack, so that is where to look for speeding it up. 1 second seems OK to me for 16249 buses...

**Comment by gplssm** [comment]
> That's far less than I expected..
> Did you use MVGD 134 resp. 3545 ?

I used 3545. Haven't noticed that ids changed. When did it happen?

**Comment by nesnoj** [comment]
> PyPSA doesn't currently have multi-threading. The majority of time should be taken by solving the sparse linear equations, which is farmed by scipy out to the C library umfpack, so that is where to look for speeding it up. 1 second seems OK to me for 16249 buses...

Thanks for clarification!

> I used 3545. Haven't noticed that ids changed. When did it happen?

The 134 refers to the new MVIEW version in model draft (new branch in dingo). I was not sure which version you are using..

**Comment by gplssm** [comment]
Can we close this one?

**Comment by nesnoj** [comment]
yupp
