### ISSUE TITLE
[FEATURE] Graphical Demonstration of Relative_Loading on dash_plot

### ISSUE THREAD

**Issue by batuhansanliii** [openego/eDisGo#304]
The relative loading of lines on the graph is depicted based on the following calculation:

https://github.com/openego/eDisGo/blob/9fae3eac3ab58713bc0a0ed66524e7eaabc2b151/edisgo/tools/plots.py#L1219-L1226

However, the calculation of relative_loading of the lines is done as follows:

https://github.com/openego/eDisGo/blob/9fae3eac3ab58713bc0a0ed66524e7eaabc2b151/edisgo/flex_opt/check_tech_constraints.py#L190-L215

As you can see from the example in the attached ipynb. file, the relative loading of example branch is bigger than 1 but shown smaller than 1 on the graph

[Relative loading_dash plot.ipynb.zip](https://github.com/openego/eDisGo/files/9593761/Relative.loading_dash.plot.ipynb.zip)

**Comment by birgits** [comment]
I think you are still using an old branch, as the plotting function is now called plot_dash(). Please pull the current dev into your branch. But anyways, you are right, it is currently not quite consistent. In PR #290 I am working on this. However, your bug should be fixed already on dev.

**Comment by batuhansanliii** [comment]
I updated the branch. Now it is better working. 
Thank you
