### ISSUE TITLE
[BUG] Missing setter for charging_points_df

### ISSUE THREAD

**Issue by nailend** [openego/eDisGo#307]
**Describe the bug**
There is a setter missing for [`topology.charging_points_df`](https://github.com/openego/eDisGo/blob/ca9663c6eb286054eb16293c57e70452ab501118/edisgo/network/topology.py#L588). I tried to set new data into this dataframe but it raised the error `AtributeError: can't set attribute` its a decorated @property. For mor info see [here](https://stackoverflow.com/a/64102244/12863591)

**Comment by nailend** [comment]
You could also use this: https://docs.python.org/3/library/collections.html#collections.somenamedtuple._replace

**Comment by birgits** [comment]
It is not supposed to be set but only to view all charging points. I'll therefore close this issue.
