### ISSUE TITLE
Type of edges

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#31]
Edges always have the type 'line'. We should make a note somewhere that this does not mean that there are no cables in edisgo but that lines and cables are only differentiated by the equipment used.

**Comment by nesnoj** [comment]
The lines from dingo keep their kind in attribute `kind` (=`line`/`cable`). This attribute is omitted in the current importer. To make life easier when it comes to evaluation (e.g. plotting with QGIS), I'd keep this attribute, hence amend the importer.
When u create a new cable (you do not create overhead lines, do you?), then you simply could set the attribute to `cable`..

**Comment by birgits** [comment]
Fixed! I added a new attribute 'kind' to the Line object specifying whether the line is an underground cable ('cable') or an overhead line ('line') and added the setting of this attribute to the importer.

`When u create a new cable (you do not create overhead lines, do you?), then you simply could set the attribute to cable..`

That's right, overhead lines are not installed in edisgo. The Baden-Württemberg study doesn't say if new overhead lines are installed in their method or not but @jochenbuehler and I decided that it is more realistic to not have new overhead lines.
