### ISSUE TITLE
Make units consistent

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#32]
We decided on the following units:
voltage - kV
current - A
power - kW
length - m
resistance - Ohm

I will add this to the documentation and use this issue to let you (@gplssm) know when I find something in the code that does not comply with the units.

**Comment by birgits** [comment]
I added a unit table to the documentation.

Some things I noticed so far:

concerning line attributes: 
- attribute "R" should be "r" (specific resistance); since we planned to use meter as unit of length, the unit of "r" should be ohm/m but is ohm/km at the moment
- "U_n" in lines needs to be in kV (has unit V right now)
- should "L" be in henry or henry/m? (right now I think it's mH/km)
- unit of "C" is farad?

concerning transformer attributes:
- "r" should be "R"
- "x" should be "X"

**Comment by nesnoj** [comment]
Thanks for digging!

> concerning line attributes:
> 
> attribute "R" should be "r" (specific resistance)

The specific resistance r includes the cross-sectional area, in our case only the length is included. If I'm not mislead, R is appropriate.

> since we planned to use meter as unit of length, the unit of "r" should be ohm/m but is ohm/km at the moment

I'd keep the unit ohm/km since it's the standard unit for lines (makes it easier for users to compare).

> "U_n" in lines needs to be in kV (has unit V right now)

Fixed in 54f0ceae24f47751bd921571cb69b391becd0ecc
**Caution:** Due to the change in LV lines from 400V to 0.4kV your code must be adapted too!

> should "L" be in henry or henry/m? (right now I think it's mH/km)
> unit of "C" is farad?

Like above, the units of L and C are standard (typically found in datasheets) and I'd stick to it. But if both of you wanna change it, I follow...

> concerning transformer attributes:
> 
> "r" should be "R"
> "x" should be "X"

Fixed in 54f0ceae24f47751bd921571cb69b391becd0ecc

**Comment by birgits** [comment]
Thank you for your fixes @nesnoj!

> The specific resistance r includes the cross-sectional area, in our case only the length is included. If I'm not mislead, R is appropriate.

Oh, you're right! So it's R for lines and transformers, but the unit is different?

> I'd keep the unit ohm/km since it's the standard unit for lines (makes it easier for users to compare).

I agree with you. But then I would also suggest to change length of lines to km.

I will adapt the documentation and check for consistency again and let you know when I pushed it!

**Comment by birgits** [comment]
One more question - do you want C in µF/km as in ding0 or in nF/km as in PyPSA?

**Comment by nesnoj** [comment]
I prefer µF (same in many datasheets, dingo) :electric_plug:
But I don't really care..

**Comment by birgits** [comment]
I pushed the units table. I forgot to change n to µ but will fix it if we agree on n.

**Comment by birgits** [comment]
I corrected the unit for capacitance in the documentation and since I haven't found anymore inconsistencies I will close this issue. Feel free to reopen in case anything else comes up!
