### ISSUE TITLE
Make LV stations the same instance in MV and LV graph

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#33]
I think that the LV stations right now are different station objects in the MV and LV graph when imported from dingo but should be the same in order to easier connect these two graphs.

**Comment by birgits** [comment]
Another thing I was wondering - will MV/LV stations have two grids in the grid attribute (MV grid and LV grid)?

**Comment by nesnoj** [comment]
> Another thing I was wondering - will MV/LV stations have two grids in the grid attribute (MV grid and LV grid)?

We did it this way in dingo and I'd implement it in the same way. I'm astonished that there was no need for these attributes yet :astonished:

**Comment by nesnoj** [comment]
> I think that the LV stations right now are different station objects in the MV and LV graph when imported from dingo but should be the same in order to easier connect these two graphs.

Yes, they are, I fully agree that both nodes should refer to the same instance.
Trying to solve this I run into different attributes (e.g. id and geom are set differently) and other stuff here (left eval window = LVstation in LV grid, right eval window = LVstation in MV grid):

![lvstations_mv_lv](https://user-images.githubusercontent.com/15910173/30483657-ef30295c-9a27-11e7-93be-e86435288695.png)

I'd try to standardize this if you agree @gplssm. Something else to pay attention to here?

**Comment by gplssm** [comment]
Thx for digging!

It was not my intention to implement anything differently there :-/ Actually, I would say I should be unifiable without too much pain. If not, pass it on to me.

**Comment by nesnoj** [comment]
Right, I'll give it a try

**Comment by nesnoj** [comment]
Ok, done in dev.
How it works: I fetch the LVStation instance from MV grid during import.

Also, I had to add a new attribute `mv_grid` to LVStation and Transformer. To my mind, it is well placed in LVStation but not in the Transformer class - we may consider to split it up into MV and LV trafo @gplssm ? But this would need some adjustments..
**In short:** Use `.grid` like before, except for LVStation and Transformer, there u gotta use: `.mv_grid` refers to MV grid, `.grid` refers to LV grid (in HV/MV station both grid attributes refer to MV grid)

I checked the project for possible references to grid and made some adjustments in `pypsa_io.py` and `reinforce_measures.py`. I tested with `network.analyze()` and `reinforce_grid()` enabled and, at least, it does not crash..
Please check if everything works as expected @gplssm @birgits

**Comment by birgits** [comment]
@gplssm we decided to use capital letters for the transformer attributes s, r and x. I could fix it in the importer but I am not sure about what else might be affected by this change (pypsa interface etc.). Could you please fix it?

**Comment by gplssm** [comment]
Yes

**Comment by gplssm** [comment]
> @gplssm we decided to use capital letters for the transformer attributes s, r and x. I could fix it in the importer but I am not sure about what else might be affected by this change (pypsa interface etc.). Could you please fix it?

Done!

**Comment by birgits** [comment]
Merci beaucoup! I will have a look at it in the afternoon.

**Comment by birgits** [comment]
Thank you @nesnoj, it works! Can we close this issue?

**Comment by nesnoj** [comment]
Yes, from my pov.
If you did not find any bugs, please close this @birgits
