### ISSUE TITLE
[Question] edisgo_simple_example.ipynb

### ISSUE THREAD

**Issue by goruiqi** [openego/eDisGo#334]
Hello, I have some question about "edisgo_simple_example.ipynb".

I used the edisgo(v0.1.1) to run "edisgo_simple_example.ipynb" by using the "eDisGo/tests/data/ding0_test_network_2" case, but there are some error. For example, the case doesn‘t have 'pypsa_version' and 'timeseries_generation_fluctuating'. Do I used the wrong case or wrong edisgo verison?

I'm looking forward to your reply.

**Comment by khelfen** [comment]
Hey @goruiqi , thank you for bringing this up! It seems like this is an issue with the newest [`PyPSA`](https://github.com/PyPSA/PyPSA) Version which was released just recently. For now we will make a new release as soon as possible (probably tomorrow).

**Comment by khelfen** [comment]
Hey @goruiqi , I just released `v0.2.0`, which you can install via [PyPI](https://pypi.org/project/eDisGo/) or from source. Let me know if anything does not work as expected.
