### ISSUE TITLE
[BUG] EDisGo.analyze(mode="mv") exports the MV/LV-Transformers into the PyPSA-Network-Object

### ISSUE THREAD

**Issue by mltja** [openego/eDisGo#338]
**Describe the bug**
EDisGo.analyze(mode="mv") exports the MV/LV-Transformers into the PyPSA-Network-Object.

**Expected behavior**
Don't import the MV/LV-Transformers because they aren't used.

**Comment by birgits** [comment]
Is not done anymore.
