### ISSUE TITLE
problems with installation of eDisGo

### ISSUE THREAD

**Issue by cannstatt** [openego/eDisGo#344]
hi there,

i have tried to install eDisGo on my windows PC via anaconda prompt. 
I don`t undestand what i have to do to get the installation started. 
In the read the docs file they say i need to download the provided eDisGo_env.yml file. But i can`t find it on Github.

I tried to copy past the code provided under the link of the  eDisGo_env.yml on the github page into anaconda prompt but an error occurred. 

Can you help me to get the installation od eDisGo started?

**Comment by mltja** [comment]
Hey @cannstatt the file is here -> https://github.com/openego/eDisGo/blob/v0.2.0/eDisGo_env.yml

You have to use conda with the command line:
https://docs.conda.io/projects/conda/en/stable/commands.html

conda env create -f eDisGo_env.yml
conda activate eDisGo_env

If you have more problems, it would be great if you can send some error messages, and maybe you can quote the part you don't understand.

Good luck
Malte

**Comment by birgits** [comment]
@cannstatt is your issue solved? If so, I would like to close this issue.
