### ISSUE TITLE
Add label for each component of the grid topology

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#36]
I propose to add the attribute `label` to class `Component`. We can use this for the PyPSA interface and for indexing data that is related to components, i.e. results data obtained from PFA.

Any objections or suggestions for improvement @nesnoj @birgits ?

**Comment by birgits** [comment]
I don't quite understand what you want to use it for but if you need it for the PyPSA interface I don't have any  objections.

**Comment by nesnoj** [comment]
Another approach is to use the `__repr__()` method to get the unique id but if this does not suit your needs, go for it!

**Comment by gplssm** [comment]
> Another approach is to use the __repr__() method to get the unique id but if this does not suit your needs, go for it!

Thx for the hint! I'll try to use the repr(). Maybe I have to change the definition of it for some components in order to distinguish the uniquely.

**Comment by gplssm** [comment]
I use the repr() and I'm quite fine with it
