### ISSUE TITLE
Change Ding0 importer: Load with only one sector

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#37]
Currently loads of sector 'industrial/retail' are modeled as loads with two keys in `load.consumption` ('industrial' and 'retail'). This is not helpful. Change to only 'industrial' or 'retail' and adjust related code like repr() of load and similar.

### To be changed at

- [x] "# TODO: remove consideration of only industrial sector" in `_pypsa_load_timeseries(network, mode=None)`. see [pypsa_io.py](https://github.com/openego/eDisGo/blob/5a77a44670edce1a49d5330f906c4687ebe1d3ca/edisgo/tools/pypsa_io.py#L708-#L721)
- [ ] Needs to be adjusted in _validate_etrago_specs in import_data.py as well.
- [x] [Needs to be removed](https://github.com/openego/eDisGo/blob/5a77a44670edce1a49d5330f906c4687ebe1d3ca/edisgo/grid/components.py#L180-#L183)
- [ ] state in What's new that these changes require data from ding0 v0.1.8dev (and following versions)

### Tested with

ids = [3040, 525, 239]

**Comment by gplssm** [comment]
Involves more and more hacking... Decided to move the [solution of this issue to Ding0](https://github.com/openego/ding0/issues/237).

**Comment by birgits** [comment]
Needs to be adjusted in _validate_etrago_specs in import_data.py as well.

**Comment by gplssm** [comment]
> Needs to be adjusted in _validate_etrago_specs in import_data.py as well.

@birgits is this still up-to-date? Cannot find any function called `_validate_etrago_specs()`

**Comment by birgits** [comment]
Nope, I deleted the ETraGoSpecs class since ego is now using the EDisGo class interface.

**Comment by gplssm** [comment]
> Nope, I deleted the ETraGoSpecs class since ego is now using the EDisGo class interface.
:+1: 

The branch `fix/#37-load-single-sector` encompasses the changes for considering loads of the sectors retail and industrial individually. Sadly, the changes change the reinforcement results :sob: 

As the reason cannot be identified, work on this issue is on hold.

**Comment by gplssm** [comment]
The [update of the description in the related ding0 issue](https://github.com/openego/eDisGo/blob/5a77a44670edce1a49d5330f906c4687ebe1d3ca/edisgo/grid/components.py#L180-#L183) made obvious that a must exist in the time series of a load (in eDisGo), because only the first sector of the consumption dictionary is considered.

**Comment by birgits** [comment]
@gplssm does [this](https://github.com/openego/eDisGo/commit/88ca73fc59f38ee7ab030f69cbd37a3b7a0e80fd) fix everything?
