### ISSUE TITLE
better place to store temp. generator data

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#41]
The data of agg. genos are currently stored in Network's attribute `_dingo_import_data` (written by dingo importer, read by geno importer) #21. To avoid spamming our main class, I need a better location here..

EDIT: If we had something like run_edisgo(), the dingo importer could return the data and pass it to the generator importer.

**Comment by birgits** [comment]
Handling of generators in aggregated areas has changed completely. They are now exported in ding0 the same way as other generators. We can therefore close this issue.
