### ISSUE TITLE
improve logging format

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#42]
The logging format is confusing - give it a better (hierarchical) structure.

**Comment by nesnoj** [comment]
Addition: Define when to use which type (info, warning, debug, error)

**Comment by gplssm** [comment]
> Addition: Define when to use which type (info, warning, debug, error)

Preferably [here](https://github.com/openego/eDisGo/blob/dev/doc/dev_notes.rst)

**Comment by nesnoj** [comment]
Yea, great page :)
But what I mean is not "where to document" (also important)  but "which type in which situation?"
E.g.: Do I use warning or error type if some generators cannot be imported?

**Comment by gplssm** [comment]
A rough proposal for logging message levels

| Level | Type of messages |
|--------|-------------------------|
|Debug|Details of algorithms and program flow|
|Info|Messages informing about steps of a eDisGo run that the user should know |
|Warning|Unintended behavior of program execution that should be known by the user. Distinguished from "error" by correct program execution is still expected/possible|
| Error | All types of unexpected behavior/misbehavior that definitely affects results such that these are wrong|

Feel free to edit. Once we agreed, we can document it in the "Dev notes".

**Comment by khelfen** [comment]
Merging issue #107

Currently, the logger is set up in the example files, eDisGo_run() and other scripts directly at the top of the file. This introduces duplication and makes it difficult to re-use logger definitions elsewhere. Additionally, there are requests for finer control of logging parameters when using the logger.

TODOs
- Create a setup function for the logger, similar to [ding0's logger](https://github.com/openego/ding0/blob/a46a76f296319406313e400a5b4ce065db96bbde/ding0/tools/logger.py#L70-#L109)
- Provide following choices to the user for parametrization of the logger
  - Custom location
  - Custom file name
  - Define loglevel individually for StreamHandler and FileHandler
- Make it possible to include log information of depending packages, such like PyPSA
