### ISSUE TITLE
performance and resources of eDisGo

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#49]
We need some improvements in terms of performance & resources:

- RAM usage of `analyze()` seems to be ~2 GB !! (3.4 GB enabled, 1.4 GB disabled)
- `analyze()` is quite slow (~28 sec. in MVGD 3545/143) of which the conversion `to_pypsa()` takes ~18 sec.
- Dingo importer is quite slow (~15 sec. in MVGD 3545/143)
- Computation time of PF (seems to be resonable, #30)
- Generator importer? TO BE DONE...

@gplssm You did some profiling, you may add more if it makes sense to you..

**Comment by gplssm** [comment]
While implementing the worst-case power flow analysis I reworked time series construction. Now, these are retrieved from the global time series instance.

A comparison with data of MVGD 28 doing the import + PFA for single timestep

| | Old|New|
|-|-----|------|
RAM| ~1450 MB|~200 MB|
|Run time| 20 sec.|18 sec.|

At least some RAM usage could be reduced.

**Comment by gplssm** [comment]
If `nodes_by_attribute()` is speeded up as asked in #53, we'll probably achieve speed-ups at several location in the code base. I close this one in favor.
