### ISSUE TITLE
Timeseries for generators

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#5]
_This task changed since initial creation._

For case 3 (_Time series w/o eTraGo_) of #60 we need normalized feedin for PV and wind power plants for each weather of the MVGD. Get this data from OEDB and save it accordingly to Timeseries() class.

**Comment by gplssm** [comment]
Time series for generators are imported now by [this method](https://github.com/openego/eDisGo/blob/7c3a50400d635917530dc5fb65e79a6c6c405f48/edisgo/grid/network.py#L203-#L207) which is called in the example.

Following TODOs are on the list

- [ ] Reshape data
- [ ] Assign to `TimeSeries` and introduce required switches
- [ ] Create time series for generators other than RES technologies: construct a synthetic time series derived from nominal capacity scaled by a factor (0..1)

**Comment by birgits** [comment]
It's working for now but we should leave this ticket open as a reminder to implement dispatch optimization with pypsa. Right now all technologies other than wind and solar have a constant dispatch of x% (right now 90%) of their nominal capacity. We could also think about leaving it as it is but using more realistic full load hours for the different technologies.

**Comment by gplssm** [comment]
I would like to close this milestone. So I assign this task to v0.0.2 which is a realistic date for implementation.
