### ISSUE TITLE
Distinguish aggr. generation by type not by subtype

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#51]
This makes sence since unavailable subtype entries are translated to 'unknow'. Thus, important information could be lost respectively capacity of different generator types could mixed up by 'unknown' ([see](https://github.com/openego/eDisGo/blob/c67299e93e5a496df6670f392d485d8bf6f2a7fb/edisgo/data/import_data.py#L394-#L404)).
While doing this, think of deleting [this code](https://github.com/openego/eDisGo/blob/c67299e93e5a496df6670f392d485d8bf6f2a7fb/edisgo/data/import_data.py#L442-#L450)

**Comment by nesnoj** [comment]
Ok, I'll wait until this one is done before I'll implement type-specific agg. generators https://github.com/openego/eDisGo/issues/21#issuecomment-331677897

**Comment by gplssm** [comment]
Ok, I'll try to fix it today...

**Comment by gplssm** [comment]
In 14751173e7bfad83438e3e03ade023f922879ee7 I restructed representation of generators in aggr. LAs. Now these are distinguished by
- Load area
- voltage level (4..7)
- generation_type
- generation_subtype

@nesnoj are you fine with this differentiation? Otherwise we could think of neglectind voltage_level and subtype if its more appropriate to your needs.

**Comment by gplssm** [comment]
See how aggr. generators are [added to the eDisGo graph](https://github.com/openego/eDisGo/blob/8651550a2c53bdeff06eea9c2d560e1c8c33d750/edisgo/data/import_data.py#L515-#L542) during the import.

**Comment by gplssm** [comment]
If any problem occurs, please re-open this issue.

**Comment by nesnoj** [comment]
I used the same method to add new agg. genos, but I did not know where to get the `la_id` from (without using very very ugly workarounds) so it's currently missing in the geno id..
I added this to my list in #21 to solve it later..

**Comment by gplssm** [comment]
Some quick ideas (that you may already had) to solve the problem of LA ids that are difficult to access

1. As far-in-the-future solution: include LA in Generators table. Should be achieved without too much effort during DP
2. Join Generators table during import with LA table. Hopefully, this could be done without a spatial join, via LVGD ids maybe? Otherwise, consider a spatial query using `ST_contains` or similar.
3. Provide the generator importer only when Ding0 data is import (or join between data sources is solve elsewhere). Then you could access the Ding0 network object, which should you provide enough information.

Maybe some of the above help you out...

**Comment by nesnoj** [comment]
Thanks for your input!

1. I agree: far in the future! ;)
2. Good idea, I think I prefer this solution..
3. I do not know how to access the ding0 network without storing it in a global way such as in Network's `_dingo_import_data` attribute..

**Comment by gplssm** [comment]
> 3. I do not know how to access the ding0 network without storing it in a global way such as in Network's _dingo_import_data attribute..

How about doing that during the generators import and deleting this attribute afterwards?

**Comment by nesnoj** [comment]
Yea, possible.
I could implement it this way and alter the place to store it later on (I'd prefer to store the other temp. import data somewhere else than in Network's attribute anyway..)
