### ISSUE TITLE
pypsa export - R and X of transformers

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#54]
In the pypsa documentation for transformer attributes it says:
Unit of R and X: Series reactance/resistance (per unit, using s_nom as base power)

We hand over R and X in Ohm. Is that correct?

**Comment by gplssm** [comment]
I already discussed [this question on the PyPSA mailing list](https://groups.google.com/forum/#!topic/pypsa/-3_-x-oqjMM). The short answer is: X and R must be provided in pu. 

The long answers includes the calculation of X and R in pu.

x_pu and r_pu determine from absolute resistance/reactance by normalizing via base impedance Z_{base}.
```
r_{pu} = R / Z_{base} 
x_{pu} = X / Z_{base} 
```

The base impedance is obtained 
```
Z_{base} = V_{trafo,primary side}^2 / S_base 
```
where S_base refers to the nominal apparent power of the transformer.

Do this calculation for one exemplary transformer size and cross-check with specifying the same transformer as transformer_type by

```
network.add("TransformerType","my TT", s_nom=..., vsc=...,...)
```

This should allow to see x_pu and r_pu in `network.transformers`.

**Comment by gplssm** [comment]
Sadly, PyPSA does not write values for X,R for standard transformers to `network.transformer`. Thus, validation cannot be done. I'm quite about the determination of r_pu, x_pu as described above, but not 100%!

Nevertheless, I implemented it  in 954943192a2d1284db1279fcf18712a006c77881 and will cross-check with @jochenbuehler.

**Comment by gplssm** [comment]
I consulted JB and he generally agreed on the calculation. But, I have to discussed two details with him...

**Comment by gplssm** [comment]
@jochenbuehler provided [this video](http://www.youtube.com/watch?v=-xLdgTGCM_s&t=2m40s) that explains how to convert resistance/reactance of transformers from absolute to pu values. It confirms the above described way of calculation
