### ISSUE TITLE
IDs of branches

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#58]
Lines have 3 different ID types:
1. IDs from dingo (following [dingo's branch ID system](https://github.com/openego/ding0/blob/65bf0153d2889c0365157de1b65d046858a6c771/ding0/core/network/grids.py#L280-L299))
2. ID is built from id of connected geno (if aggregated)
3. ID is set to large random number (temp. solution for geno connection)

**General solution:**
Ad-hoc ID using repr() of the 2 connected nodes, e.g. `'line_' + repr(node1) + '_' + repr(node2)`.

**Comment by nesnoj** [comment]
Note: The ids of newly connected branches in `import_generators()` are set randomly.
This leads to id duplicates (some equal in MV and LV) due to multiple seeding. Therefore, the seed was temporarily changed, see `connect.py`. Switch back to seed from config as soon as this issue is resolved.

**Comment by gplssm** [comment]
I tested the new representative for Lines

``` 
def __repr__(self):
    nodes = sorted(self.grid.graph.nodes_from_line(self),
                   key=lambda _: repr(_))
     return '-'.join(['Line',
                      repr(nodes[0]),
                     repr(nodes[1])])
```
and had the same error during 3rd round of PFA with 135 (Ding0 data version 20171020130423). With Ding0 data version 20171025134031 I had different issues :man_facepalming: 

Actually, I have to think about the ID concept of lines more. I think with the implementation above it isn't used that much, because the pypsa_io somehow manually uses similar IDs/names.

**Comment by nesnoj** [comment]
The solution above has 2 advantages:
1. The user can easily identify the nodes the line is connected to
2. We don't have to struggle to achieve unique ids

Even though it does not affect the pypsa representation (if I got u right), I'd try to implement it this way (as long as there're no more problems popping up.. ;).
Thanks for review!

if you cannot track down the actual bug, we may have to swallow the bitter pill and use a central function to assign unique ids (as in dingo but with ad-hoc-assignment).

**Comment by nesnoj** [comment]
Not sure if this one can be postponed to v0.0.2 .
@gplssm Are more MVGDs affected than the 2 mentioned above? If it's just a small amount, I tend not to fix it in v0.0.1 .

**Comment by birgits** [comment]
@nesnoj is this still relevant?

**Comment by birgits** [comment]
When adding a new line it is now checked, if the representative is unique and otherwise a new unique representative is created. The buses connected by the line are part of the representative.
