### ISSUE TITLE
grid expansion costs for conv. PP

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#59]
Discussing how to update our grids with changing conventional powerplant IDs (cf. https://github.com/openego/data_processing/issues/175#issuecomment-334440918) with @wolfbunke, the simplest way is to disconnect all of the existent PP of SQ and connect the new ones (since it is very complicated to identify unique PP).
Hence, new cables would be laid to all PP which lead to different costs (since in the update-case, maybe not all of the cables would be reinforced).

We have 218 conv. plants in v_levels 4...7 (cum. cap =  2494 MW) in SQ and 136 plants in v_levels 4...7 (cum. cap =  1479 MW) in NEP2035.
Compared to the costs of grid expansion due to increased RES capacities, these **costs are probably negligible** (and many plants are shut down). If we decide to accept this small error, it would be much easier for me to implement.

What do you think @gplssm @birgits?

**EDIT:** UPDATED NUMBERS OF PP

**Comment by nesnoj** [comment]
Addition: In case we fully neglect these costs, the new lines
- are to be tagged as "please-do-not-reinforce-@birgits" **OR**
- are treated as a new line as in RES connection (cf. proposed method in https://github.com/openego/eDisGo/issues/45#issuecomment-334729750)

**Comment by nesnoj** [comment]
2nd Addition: We're only talking about v_levels 4+5 since there're no conv. PP in 6+7.

RES in NEP (v_levels 4+5): ~64k (92 GW) 
--> The number of conv PP is only ~0.2% of the number of RES in NEP. Even with greater cable costs for voltage level 4 (and thus over-/underestimation of grid exp. costs) this error should be less than 1%.

**Decision:** If there're no objections, I will neglect possibly existing lines (created in dingo) and do a normal connection (as done for new RES) and add the costs to the total cost DF as discussed in #45.

**Comment by gplssm** [comment]
I do not fully understand it (in particular the reason for changing conv. PP IDs). Anyway, I trust you @nesnoj finding a good solution!

**Comment by birgits** [comment]
Can we close this?

**Comment by nesnoj** [comment]
No, it is one ToDo in #21 and I'll close it as soon as I've done it..

**Comment by nesnoj** [comment]
As I haven't solved this one, some statistics:
```
SELECT scenario, voltage_level, count(*), sum(capacity)
  FROM supply.ego_dp_conv_powerplant
  WHERE version = 'v0.3.0' AND voltage_level IN (4,5,6,7)
  GROUP BY scenario, voltage_level
  ORDER BY scenario, voltage_level;
```
gives
```
scenario;voltage_level;count;capacity_sum
"NEP 2035";4;120;1325
"NEP 2035";5;16;36.8
"NEP 2035";7;271;0
"Status Quo";4;200;2481.1125
"Status Quo";5;21;48.1
"Status Quo";6;1;0.1
```

- v_level 4: We do not care too much as it does not affect topology (maybe some new lines to HV/MV station) -> negligible!
- v_level 5+6: Only minor changes here due to decommissioning -> negligible?!
- v_level 7: The 271 datasets are from PP which will be decommissioned in NEP2035 -> ok

So we are in a nice position here!
But: One must be aware that the capacities (+timeseries) will differ between the 2 tools, this already came up here @maltesc: https://github.com/openego/eGo/issues/11#issuecomment-373122903

Opinions, @gplssm @birgits?

**Comment by birgits** [comment]
Thank you @nesnoj for your quick help! Is the unit MW? And are decommisioned capacities included in the sum as negative capacities?

**Comment by nesnoj** [comment]
- Yes, capacity is in MW.
- No, decommissioned pp appear in `count` but not in `capacity_sum` (as u can see in NEP 2035 with v_level 7). Accordingly,
```
SELECT scenario, voltage_level, count(*), sum(capacity) as capacity_sum
  FROM supply.ego_dp_conv_powerplant
  WHERE version = 'v0.3.0' AND voltage_level IN (4,5,6,7) AND capacity>0
  GROUP BY scenario, voltage_level
  ORDER BY scenario, voltage_level;
```
gives
```
scenario;voltage_level;count;capacity_sum
"NEP 2035";4;120;1325
"NEP 2035";5;16;36.8
"Status Quo";4;200;2481.1125
"Status Quo";5;21;48.1
"Status Quo";6;1;0.1
```

**Comment by birgits** [comment]
I am not sure, if the issue with changing PP IDs was solved but we now import conventional PP for the future scenarios as well. If IDs change, all existing conventional PP will be disconnected and newly connected. As the evaluation above showed, it should be negligible. I will therefore close this issue. We should however keep this in mind for the new dataset in eGo^n.

Some further information: When generators are disconnected it is checked if they were connected to a stub and the stub will be removed as well. Thus, if the same generator is again integrated into the grid, the stub will be newly added. When calculating grid expansion costs, it can be chosen if this should be included in the total costs or not.
