### ISSUE TITLE
Generator time series w/ and w/o eTraGoSpecs

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#60]
In eDisGo four types of power flow analysis parametrization are envisaged. The parametrization is mainly defined by the time series provided for components of the power system. The four types comprise of two groups: one including targets set by eTraGo, one without. In each group a worst-case anlysis and an analysis based on actual time series should be provided.

The following table provides an overview on how individual groups of generator types are modeled depending on the chosen "Type of PFA".

| Type of PFA | PV and wind | Conv. Technologies | Storages |
|-----------------|-----------------|---------------------------|-------------|
| Worst-case w/o eTraGo | 1 time step analyzed (feedin case); set points derived from nominal capacity | _see "PV and wind"_ | Storage representation not included |
| Worst-case w/ eTraGo | _tbd_ | _tbd_ | _tbd_ |
| Time series w/o eTraGo | 1 year,  1 hourly time series (or subset of these); time series provided normalized feedin data| Dispatch is determined flexibly by setting max. power of each component | Dispatch is determined flexibly by setting max. power of each component |
| Time series w/ eTraGo | Scale-down cumulative eTraGo dispatch uniformly to each component of a generator type | Scale-down cumulative eTraGo dispatch uniformly to each component of a generator type | Scale-down cumulative eTraGo dispatch uniformly to each component of a storage type | 

Type 4, namely _Time series w/ eTraGo_, can be realized in different ways. Cumulative dispatch of each component of a generator type can be matched by different distributions of power generation across available generators.
The approach described in the table above assumes dispatch is uniformly distributed among all generators of a type. Hence, the normalized feedin is the same for all generators of one type.
A potential alternative may be to determine RES dispatch by feedin data and model other generators flexible supplemented by a global constraint ensuring that match of eTraGo cumulative dispatch time series.

One big advantage of the proposed procedure above is that we can keep everything behind the TimeSeries() the same as implemented now (this is at least true for case 1 + 4). We just have to take care normalized time series are provided via this class.

### Things to clarify

1. Where does the switching between types of PFA takes place?
2. How is cumulative dispatch provided by _eTraGoSpecs_ scaled down to a single generator? A proposal: _eTraGoSpecs_ provides a method to convert absolute cumulative dispatch to a normalized time series for each generator type. Nominal capacity is provided either (1) by _eTraGoSpecs_ or (2) is collected from the grid topology data.

**Comment by maltesc** [comment]
The eGo function [get_etragospecs()](https://github.com/openego/eGo/blob/features/specs/ego/tools/specs.py) has been implemented. It reads eTraGo results from the database and returns an ETraGoSpecs object (defined by eDisgo).

In order to test the function, the eDisGo-internal usage of ETraGoSpecs needs to be implemented.

**Comment by maltesc** [comment]
I tested the [get_etragospecs_from_db()](https://github.com/openego/eGo/blob/features/specs/ego/tools/specs.py) function with the current eTraGo results (in model_draft) and eDisGo etrago_timeseries branch. 
@birgits: in some cases an error occurs with 'other' generator type. I can't access the data today and will specify the issue soon. Howerver, perhaps you already have a hint...
