### ISSUE TITLE
Units in cost.csv

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#61]
The `example.py` writes a file `cost.csv` detailing about reinforced equipment incl. cost of extending it. Currently, numbers come without units. Please add units to the file in the following format

```
,type,length,quantity,total_costs
#-, <unit1>, <unit2>, <unit3>
``` 
Then, we can parse it with `pandas.read_csv(comment='#')`.

**Comment by birgits** [comment]
Done :)
