### ISSUE TITLE
How to deal with program abortion?

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#62]
Currently, when grid reinforcement fails for some reason, eDisGo is aborted by `sys.exit()`. Running eDisGo across several hundred of grids, I discovered an issue with that. Even when I catch exceptions from `network.reinforce()`, eDisGo aborts due to `sys.exit()`. Is there a smarter way to stop the program, but being able to loop over several grids while catching exceptions by a `try` and `except` statement?
@birgits what do you think? And apart from only catching the error and properly aborting eDisGo, how should we solve the issue of not being able to resolve the issue of exceeded hosting capacity by grid reinforcement? This is as well a question for @jochenbuehler 

@nesnoj your opinion is as usual highly appreciated!

**Comment by nesnoj** [comment]
>  Even when I catch exceptions from network.reinforce(), eDisGo aborts due to sys.exit(). Is there a smarter way to stop the program, but being able to loop over several grids while catching exceptions by a try and except statement?

I do not know another way of catching them but with try...except.
Are all exception types really catched in `network.reinforce()`? As far as I can see, most statements in reinforce catch `KeyError` only. A better way is to collect all error types raised during execution of all networks and catch them explicitly.. Alternatively, to catch 'em all, leave the type blank and get more info of the error type using `sys.exc_info()`.

> how should we solve the issue of not being able to resolve the issue of exceeded hosting capacity by grid reinforcement?

It would be great to have a list of reasons why it fails to assess which ones are acceptable (e.g. agg. LA only) and which ones are not.

**Comment by nesnoj** [comment]
>  Is there a smarter way to stop the program, but being able to loop over several grids while catching exceptions by a try and except statement?

I'm still not sure if I got it right, but you can use `pass` in the `except`-block to continue the program execution (as done in [this example](https://github.com/openego/eDisGo/blob/1eada485cf27e4cec7581172b7cbf6f7cadc1dea/edisgo/data/import_data.py#L1532-L1544)).

**Comment by gplssm** [comment]
Thanks for the example! I think you got me right. In the case I'm talking about the try statement contains a function with several subfunctions. Somewhere deep inside these nested function calls the program should be aborted due to issues with grid reinforcement. `pass` would be an option if `logging.error()` is called before. I discussed with @birgits and she'll try to use `raise SomeAppropriateException(<message>)` instead of `pass`. Doing this results in appropriate reporting about the issue and can be caught by `except Exception as e`.

**Comment by gplssm** [comment]
> It would be great to have a list of reasons why it fails to assess which ones are acceptable (e.g. agg. LA only) and which ones are not.

True! But I think we can postpone it until generator connection is ready. Probably, there will be more issues. In addition, I could hand over a list of Ding0 issues that are caught during a Ding0 run :smirk: Just kiddin'!

**Comment by birgits** [comment]
@gplssm can we close this or did you stumble upon anything else when you ran grid expansion for all dingo grids?

**Comment by birgits** [comment]
We decided to raise the MaximumIterationError and report unresolved issues. The example scripts needs to catch the error.

**Comment by gplssm** [comment]
In addition to the standard example, [run_edisgo_worst_case()](https://gist.github.com/gplssm/e0fd6cb99f7e8c1eed3fd4a4e325dde0#L23-#L129) needs to be adapted.

**Comment by birgits** [comment]
I pushed the changes to dev but still need to adapt the gist (example in dev is already adapted to catch MaximumIterationError).

**Comment by birgits** [comment]
Gist is adapted so I'll close this issue.
