### ISSUE TITLE
fallback line length

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#67]
I propose to use 1m to connect aggregated units and as default "fallback" line length. Accordingly, I changed some lines in 39d510ed754a0e36dc754c875f7fb1c2250fc965.

@gplssm Can we change this one too?
https://github.com/openego/eDisGo/blob/7700d6e48338077861c56bde660917986e239484/edisgo/grid/tools.py#L212

**Comment by gplssm** [comment]
My decision for this value was closely based on `from random import ...` 1m is fine for me
