### ISSUE TITLE
Log grid issues/information

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#68]
It'd be great to have more information in the results about the grid / problems edisgo stumbled upon. This helps to evaluate and categorize our results.

We should consider error codes which could be attached to the Result class, e.g.
```
[10] MVGD-related
11 Grid contains agg. LA only
...
[20] Generator-related
21 More than XXX% of LV grids contain more generators than loads
22 Some generators have no geom
...
```

This might be a task for a student?

**Comment by birgits** [comment]
@nesnoj could you specify this a bit more? What do you mean with problems?

**Comment by nesnoj** [comment]
I think this is outdated
