### ISSUE TITLE
Distinguish cost of grid extension

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#72]
As far as I understood during grid extension cost calculation, we don't distinguish cost for reinforcement w/ and w/o 2035 generators yet.

In order to do - and to provide a proper dataset for Manuel - we should distinguish here. Hence, we have to modify the eDisGo run to do one extra round of PFA + grid reinforcement prior to import of generators. Once, we adapting the example, we can think of using [this eDisGo run function](https://gist.github.com/gplssm/14d3f1305447ff91574cd89c53cbcd7c#L15-#L79) for the example as well and just call it from `if __name__ == '__main__':`. Therefore, we should find a good location for this function.

@birgits assign it back to me if you cannot take care about it now

**Comment by nesnoj** [comment]
Just to raise a general question:
Hmm, Dingo should provide working grids which do not require additional reinforcements in status quo grids. The only differences (and reason y additional grid extension measures may be performed) I see are acceptable thresholds for current and voltage in eDisGo which differ from those used in Dingo. Right?

Do we want to add these "[threshold](https://xkcd.com/323/)-specific" costs to our grid expansion costs?

**Comment by birgits** [comment]
I adapted the example to first calculate grid expansion costs without new generators, then add new generators and perform grid expansion again. @gplssm will you move the example to your run functions?

> Do we want to add these "threshold-specific" costs to our grid expansion costs?

Could we use the same thresholds? @nesnoj do you know which ones are different? I couldn't find the dingo configs.

**Comment by gplssm** [comment]
Thanks for the implementation in the example.py. I adapted run_eDisGo.py.

Regarding the thresholds, actutally we cannot apply the same parameters as in Ding0. There, we analyzed MV and LV separately with individual threshold. Those were related to nominal voltage at stations in both levels which isn't the case in eDisGo for LV stations.
I would be fine applying the 10% threshold at all nodes which is compliant with the current regulatory framwork.

@nesnoj if you don't have further concerns, we can close this one.

**Comment by birgits** [comment]
>  There, we analyzed MV and LV separately with individual threshold.

But wouldn't that lead to more grid expansion than analyzing the grids together? A maximum of 10% cannot be exceeded in both cases plus when analyzing the grids separately voltage deviation in MV must be smaller than 10%.

**Comment by nesnoj** [comment]
I like the solution to reinforce the grid at the beginning and neglecting costs.
However, we cannot state that we use the original grids from dingo - it bothers me to do something "on the quiet" (kind of..). We can only argue that in eDisGo, different thresholds (+methods to check it) apply..

An optimal solution was to implement this grid expansion step in dingo but I guess this is currently not realizable..

I propose to check how many components are reinforced within this step. As the simplified methods in dingo are supposed to work more failsafe than the combined one in eDisGo, there shouldn't be too many.  If we find out that extensive measures are performed, we may have to review the current approach.
Please keep this issue open.

**Comment by birgits** [comment]
Did we decide anything here? I don't remember... Did we want to solve this in dingo? If we want to calculate grid expansion costs before generator import to have working dingo grids we can leave it as it is and close this ticket.

**Comment by birgits** [comment]
Until this is solved in dingo we decided to provide a simple example of the edisgo usage explaining that dingo grids are currently not stable and that grid expansion is therefore conducted once before generator import and once after generator import.

**Comment by birgits** [comment]
I added a small explanation to the example and added a minimum working example using etrago specs to the documentation.
