### ISSUE TITLE
Resolve issues with eDisGo installation

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#78]
Recently I installed a fresh eDisGo and discovered a bunch of issues related to the installation of eDisGo,

Here's a quick overview as reminder for a fix 

1. Cannot import 'connection' in ego.io (v0.2.0). Solution: ego.io dev branch (v0.3.0)
2. Cannot import from 'oemof' (v0.0.5). Solution install oemof.db==0.0.4
3. Pandas 0.19.2 is installed, does not work with Ding0/eDisGo. Solution install pandas==0.20.3
4. ~/.egoio and config.ini are not created automatically
5. Netwokx version 2.0 is incompatible with ding0, pip3 install -U "networkx<2.0"
6. Scipy 1.0 incompatible with pypsa, installed: pip3 install -U "scipy<1.0"
7. Ding0 version from pypi (which is linked by eDisGo) is outdated -> A new release and dependency update requried

**Comment by gplssm** [comment]
**Update**
1. Needs to be resolved in Ding0
2. There is a conflict with ego.io dependencies: Ding0 requires oemof.db==0.0.4 while ego.io requires exactly oemof.db==0.0.5. Discussion about changing dependency in ego.io can be found in https://github.com/openego/ego.io/issues/41
3. Unclear where pandas==0.19.2 is determined. Requires further investigation
4. Will be fixed by the new connection provide with ego.io v0.3.0. Until then, this has to be resolved manually
5. Resolved in https://github.com/openego/eDisGo/tree/fix/%2378-installation-issues by limiting to versions less than 2.0
6. This issue should appear when PyPSA is installed standalone. Try to install PyPSA and check if the issue still occurs! A solution could be to explicitly include scipy as a dependency of eDisGo restricting to versions < 1.0 
7. Until a new Ding0 release is available a link to a commit in the branch "use-data-from-v0.3.0pre1" will do the job

**Comment by boltbeard** [comment]
@gplssm 

while installing oemof.db 0.0.4 for
> 2. Cannot import from 'oemof' (v0.0.5). Solution install oemof.db==0.0.4

the side effect is that it forces the installation/depreciation of pandas to version 0.19.1 and also shapely to version higher than 1.5.12.

The dependency of pandas gets solved with
> 3. Pandas 0.19.2 is installed, does not work with Ding0/eDisGo. Solution install pandas==0.20.3

shapely still has a the dependency conflict in `'shapely >= 1.5.12, <= 1.5.12' ` in setup.py

**Comment by boltbeard** [comment]
Watch out for dependencies from branch features/etrago_timeseries (workalendar, demandlib)

**Comment by gplssm** [comment]
1. Done by including a new (pre-)version of Ding0 that includes a pre-version of ego.io
2. Done! Entirely removed
3. Pandas is now consistently present in version 0.20.3
4. Works now
5. Already resolved
6. Workaround: list "scipy<1.0" as dependency in ding0
7. see (1)

To get it finally done, replace the preversions by published ones. Therefore, start with releasing ego.io, then ding0 (with released ego.io as dependency) and finally update ding0 dependency in eDisGo and release it.
