### ISSUE TITLE
Inspect worst-case grid extension cost data

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#80]
- [ ] Inspect average line load/voltage at nodes for final Ding0 grids (e.g. distribution including Ding0's predefined threshold) and compare with resulting grid extension cost
- [x] Correct MV/LV transformer parameters, [see here](https://github.com/openego/ding0/issues/240) this should affect resulting cost not too much
- [ ] Inspect critical nodes/edges returned by Ding0
    - [ ] Exclude grids that contain such nodes/edges
    - [ ] Find the cause for remaining issues after grid reinforcement in Ding0
- [ ] Cross-check parameters handed over to PyPSA in eDisGo
- [ ] Re-Check grid expansion of Ding0 and eDisGo, e.g. i) using sample grids, ii) correlate grid expansion measures with number of critical nodes/lines
Does the ring split (at 2/3 of length) part may cause non-linearities in some results? (contrary to adding new lines)
- [ ] Re-check generator connection in eDisGo @nesnoj
- [ ] Check if assumptions on scale factors in Ding0 and eDisGo match: For generators, 1 in Ding0, 0.9/0.95 in eDisGo
- [ ] Try to exclude MVGD which...
    - [ ] ...contain only agg. LAs
    - [ ] ...contain at least 1 agg. LA

**Comment by nesnoj** [comment]
I added some stuff above.
+Could you please provide your ipython script?
+Is all of the needed data located at `/data/Ding0/`?

**Comment by gplssm** [comment]
> +Is all of the needed data located at /data/Ding0/?

Yes.

**Comment by birgits** [comment]
I'll close this in favour of #134.
