### ISSUE TITLE
Unify Scenario.name and Scenario.scenario_name

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#84]
I guess there was some work in parallel or I overlooked Scenario.name...

@birgits I intended to refer to scenario names like "NEP 2035" with `scenario_name`. Was your intention with Scenario.name the same?

**Comment by birgits** [comment]
I think @nesnoj added the _name attribute when he first created this class. I am not sure what his intention was but as far as I can tell it isn't used anywhere so we can either delete it and keep scenario_name or the other way around.

**Comment by nesnoj** [comment]
Hmm, I cannot remember but it is quite likely to blame me.. ;)
As written in the docstring, it helps to remind which scenario is used, e.g. `feedin case weather 2011`.
I could not find the `Scenario.scenario_name` attribute you mentioned..

This leads to a general question:
A scenario is defined by a lot of different parameters which should be linked to / contained in this object. Is this concept implemented consequently? (to anticipate: no, it isn't - example: We store all of the config values in `Network.config` - even those ones from the scenario file..)
Do we want to keep all scenario-related stuff in the `Scenario` object?

**Comment by gplssm** [comment]
The `scenario_name` is now only used for defining the input of the generator import and it is renamed to `generator_scenario`.
The `Scenario` class was removed entirely during restructuring #97.
