### ISSUE TITLE
dp v0.3.0 release - data backup in v0.3.0pre1

### ISSUE THREAD

**Issue by nesnoj** [openego/eDisGo#85]
The new data_processing (DP) v0.3.0 is just around the corner and accordingly, the current datasets will be recreated. During the run, the data in schema model_draft won't be accessible. This affects dingo as well as eDisGo.

I did a backup of the current data and released the version `v0.3.0pre1` (to do this, some stuff had to be done in DP: https://github.com/openego/data_processing/issues/189, https://github.com/openego/data_processing/issues/185). Consequently, **eDisGo** had to be adapted to use this version: **Please use branch `features/use-data-from-v0.3.0pre1` as from now to make sure not to be affected by the DP run!** As soon as `v0.3.0` is finished, I'll merge the changes into `dev`.

**Notes:**
- To get the new table defs, make sure you use the branch `features/use-data-from-v0.3.0pre1` of **ego.io**!
- Don't forget to delete your **configs** in order to get the new DB table defs from eDisGo.

Is anyone using **Dingo** with a DP version from model_draft ? (this is the case if you are working in the branch `features/adapt-to-powerplant-mviews-dp-v0.3.0`). Please let me know and I will adapt Dingo too...

**Comment by nesnoj** [comment]
Can we close this one?

**Comment by gplssm** [comment]
Yep, as I do the release right at the moment...
