### ISSUE TITLE
Upgrade PyPSA to 0.11.0

### ISSUE THREAD

**Issue by gplssm** [openego/eDisGo#87]
We decided to align versions of dependencies in eTraGo and eDisGo

**Update**

Compare results with PyPSA v0.10.0 to results obtained when using PyPSA v0.11.0 before.

**Comment by boltbeard** [comment]
After installation of eDisGo, installing PyPSA v0.11.0 causes no problems
Test needed :
- [x] Basic test with one small network : Works
- [ ] Check and compare outputs
