### ISSUE TITLE
Revise eDisGo input data

### ISSUE THREAD

**Issue by birgits** [openego/eDisGo#97]
Right now possible inputs for eDisGo and how they are processed is very confusing and opaque(not transparent). We need to identify the different use cases and revise the code to make the usage of eDisGo clearer.

**Comment by boltbeard** [comment]
I'd encourage editing this  comment maybe and add to or remove the of things below that may be relevant to have a closer look at and discuss?

Input data that needs revision:

- Ding0 pickled files?
- Load Timeseries?
- Feedin Timeseries?
- other data possibly accessed from sources other than oedb?

**Comment by birgits** [comment]
I finished the restructuring and would like to close this issue if you agree @gplssm and @boltbeard. Any further issues can be discussed in new, more specific issues.
